package org.fosstrak.capturingapp
 
import org.fosstrak.capturingapp.util.Util; 
import org.fosstrak.ale.xsd.ale.epcglobal.ECReport;
import org.fosstrak.ale.xsd.ale.epcglobal.ECReports;
import org.fosstrak.capturingapp.util.SimpleEPCISDocument;
import org.fosstrak.epcis.model.ActionType;

import function org.fosstrak.capturingapp.util.Util.extractEPC;

// the global collector for all the EPCIS documents for further processing.
global java.util.List epcisResults


rule "Create EPCIS event from EPCs"
	dialect "java"
	when
		$reports : ECReports()
	then
	
		SimpleEPCISDocument simpleDocument = new SimpleEPCISDocument();
		simpleDocument.addObjectEvent(
			extractEPC(Util.selectRawHex, $reports), 
			ActionType.ADD, 
			"urn:fosstrak:demo:bizstep:testing", 
			"urn:fosstrak:demo:disp:testing",
			"urn:fosstrak:demo:rp:1.1",
			"urn:fosstrak:demo:loc:1.1"
			);
		epcisResults.add(simpleDocument.getDocument());
end

