/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Fosstrak (www.fosstrak.org).
 *
 * Fosstrak is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Fosstrak is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Fosstrak; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.05 at 05:03:34 PM CEST 
//


package org.fosstrak.reader.rprm.core.msg.command;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.fosstrak.reader.rprm.core.msg.command.Command;
import org.fosstrak.reader.rprm.core.msg.command.DataSelectorCommand;
import org.fosstrak.reader.rprm.core.msg.command.EventTypeCommand;
import org.fosstrak.reader.rprm.core.msg.command.FieldNameCommand;
import org.fosstrak.reader.rprm.core.msg.command.NotificationChannelCommand;
import org.fosstrak.reader.rprm.core.msg.command.ReadPointCommand;
import org.fosstrak.reader.rprm.core.msg.command.ReaderDeviceCommand;
import org.fosstrak.reader.rprm.core.msg.command.SourceCommand;
import org.fosstrak.reader.rprm.core.msg.command.TagFieldCommand;
import org.fosstrak.reader.rprm.core.msg.command.TagSelectorCommand;
import org.fosstrak.reader.rprm.core.msg.command.TriggerCommand;
import org.fosstrak.reader.rprm.core.msg.command.TriggerTypeCommand;
import org.w3c.dom.Element;


/**
 *  This element defines a reader protocol command. The
 *                 commands are grouped by the object they belong to. To specify the object a command
 *                 relates to, the name of the object is used. Therefore, all commands that return the
 *                 name of the object become useless, since the name must be known before it can be
 *                 queried. All the names of a particular object type are global irrespective of where
 *                 they belong to. Hence names need to be unique within their object type. For example,
 *                 a DataSelector is identified by its name, irrespective of which notification channel
 *                 it belongs to. All the commands are encoded by its straight forward conversion from
 *                 UML notation. Each command is wrapped in its object type and contains its parameters
 *                 as child elements. 
 * 
 * <p>Java class for command element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="command">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="targetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;choice>
 *             &lt;element name="readerDevice" type="{urn:epcglobal:rp:xsd:1}ReaderDeviceCommand"/>
 *             &lt;element name="source" type="{urn:epcglobal:rp:xsd:1}SourceCommand"/>
 *             &lt;element name="ReadPoint" type="{urn:epcglobal:rp:xsd:1}ReadPointCommand"/>
 *             &lt;element name="trigger" type="{urn:epcglobal:rp:xsd:1}TriggerCommand"/>
 *             &lt;element name="tagSelector" type="{urn:epcglobal:rp:xsd:1}TagSelectorCommand"/>
 *             &lt;element name="notificationChannel" type="{urn:epcglobal:rp:xsd:1}NotificationChannelCommand"/>
 *             &lt;element name="dataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorCommand"/>
 *             &lt;element name="eventType" type="{urn:epcglobal:rp:xsd:1}EventTypeCommand"/>
 *             &lt;element name="triggerType" type="{urn:epcglobal:rp:xsd:1}TriggerTypeCommand"/>
 *             &lt;element name="fieldName" type="{urn:epcglobal:rp:xsd:1}FieldNameCommand"/>
 *             &lt;element name="tagField" type="{urn:epcglobal:rp:xsd:1}TagFieldCommand"/>
 *             &lt;any/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "targetName",
    "readerDevice",
    "source",
    "readPoint",
    "trigger",
    "tagSelector",
    "notificationChannel",
    "dataSelector",
    "eventType",
    "triggerType",
    "fieldName",
    "tagField",
    "any"
})
@XmlRootElement(name = "command")
public class Command {

    protected String id;
    protected String targetName;
    protected ReaderDeviceCommand readerDevice;
    protected SourceCommand source;
    @XmlElement(name = "ReadPoint")
    protected ReadPointCommand readPoint;
    protected TriggerCommand trigger;
    protected TagSelectorCommand tagSelector;
    protected NotificationChannelCommand notificationChannel;
    protected DataSelectorCommand dataSelector;
    protected EventTypeCommand eventType;
    protected TriggerTypeCommand triggerType;
    protected FieldNameCommand fieldName;
    protected TagFieldCommand tagField;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the targetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * Sets the value of the targetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetName(String value) {
        this.targetName = value;
    }

    /**
     * Gets the value of the readerDevice property.
     * 
     * @return
     *     possible object is
     *     {@link ReaderDeviceCommand }
     *     
     */
    public ReaderDeviceCommand getReaderDevice() {
        return readerDevice;
    }

    /**
     * Sets the value of the readerDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReaderDeviceCommand }
     *     
     */
    public void setReaderDevice(ReaderDeviceCommand value) {
        this.readerDevice = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceCommand }
     *     
     */
    public SourceCommand getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceCommand }
     *     
     */
    public void setSource(SourceCommand value) {
        this.source = value;
    }

    /**
     * Gets the value of the readPoint property.
     * 
     * @return
     *     possible object is
     *     {@link ReadPointCommand }
     *     
     */
    public ReadPointCommand getReadPoint() {
        return readPoint;
    }

    /**
     * Sets the value of the readPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadPointCommand }
     *     
     */
    public void setReadPoint(ReadPointCommand value) {
        this.readPoint = value;
    }

    /**
     * Gets the value of the trigger property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerCommand }
     *     
     */
    public TriggerCommand getTrigger() {
        return trigger;
    }

    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerCommand }
     *     
     */
    public void setTrigger(TriggerCommand value) {
        this.trigger = value;
    }

    /**
     * Gets the value of the tagSelector property.
     * 
     * @return
     *     possible object is
     *     {@link TagSelectorCommand }
     *     
     */
    public TagSelectorCommand getTagSelector() {
        return tagSelector;
    }

    /**
     * Sets the value of the tagSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagSelectorCommand }
     *     
     */
    public void setTagSelector(TagSelectorCommand value) {
        this.tagSelector = value;
    }

    /**
     * Gets the value of the notificationChannel property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationChannelCommand }
     *     
     */
    public NotificationChannelCommand getNotificationChannel() {
        return notificationChannel;
    }

    /**
     * Sets the value of the notificationChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationChannelCommand }
     *     
     */
    public void setNotificationChannel(NotificationChannelCommand value) {
        this.notificationChannel = value;
    }

    /**
     * Gets the value of the dataSelector property.
     * 
     * @return
     *     possible object is
     *     {@link DataSelectorCommand }
     *     
     */
    public DataSelectorCommand getDataSelector() {
        return dataSelector;
    }

    /**
     * Sets the value of the dataSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSelectorCommand }
     *     
     */
    public void setDataSelector(DataSelectorCommand value) {
        this.dataSelector = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link EventTypeCommand }
     *     
     */
    public EventTypeCommand getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTypeCommand }
     *     
     */
    public void setEventType(EventTypeCommand value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the triggerType property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerTypeCommand }
     *     
     */
    public TriggerTypeCommand getTriggerType() {
        return triggerType;
    }

    /**
     * Sets the value of the triggerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerTypeCommand }
     *     
     */
    public void setTriggerType(TriggerTypeCommand value) {
        this.triggerType = value;
    }

    /**
     * Gets the value of the fieldName property.
     * 
     * @return
     *     possible object is
     *     {@link FieldNameCommand }
     *     
     */
    public FieldNameCommand getFieldName() {
        return fieldName;
    }

    /**
     * Sets the value of the fieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldNameCommand }
     *     
     */
    public void setFieldName(FieldNameCommand value) {
        this.fieldName = value;
    }

    /**
     * Gets the value of the tagField property.
     * 
     * @return
     *     possible object is
     *     {@link TagFieldCommand }
     *     
     */
    public TagFieldCommand getTagField() {
        return tagField;
    }

    /**
     * Sets the value of the tagField property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagFieldCommand }
     *     
     */
    public void setTagField(TagFieldCommand value) {
        this.tagField = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
