/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Accada (www.accada.org).
 *
 * Accada is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Accada is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Accada; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.05 at 05:03:34 PM CEST 
//


package org.accada.reader.rprm.core.msg.command;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.accada.reader.rprm.core.msg.command.HexStringListType;
import org.accada.reader.rprm.core.msg.command.NoParamType;
import org.accada.reader.rprm.core.msg.command.ReadPointListParamType;
import org.accada.reader.rprm.core.msg.command.SourceCommand;
import org.accada.reader.rprm.core.msg.command.TagFieldValueListParamType;
import org.accada.reader.rprm.core.msg.command.TagSelectorListParamType;
import org.accada.reader.rprm.core.msg.command.TriggerListParamType;
import org.accada.reader.rprm.core.msg.command.SourceCommand.AddReadPoints;
import org.accada.reader.rprm.core.msg.command.SourceCommand.AddReadTriggers;
import org.accada.reader.rprm.core.msg.command.SourceCommand.AddTagSelectors;
import org.accada.reader.rprm.core.msg.command.SourceCommand.Create;
import org.accada.reader.rprm.core.msg.command.SourceCommand.GetReadPoint;
import org.accada.reader.rprm.core.msg.command.SourceCommand.GetReadTrigger;
import org.accada.reader.rprm.core.msg.command.SourceCommand.GetTagSelector;
import org.accada.reader.rprm.core.msg.command.SourceCommand.Kill;
import org.accada.reader.rprm.core.msg.command.SourceCommand.RawReadIDs;
import org.accada.reader.rprm.core.msg.command.SourceCommand.Read;
import org.accada.reader.rprm.core.msg.command.SourceCommand.ReadIDs;
import org.accada.reader.rprm.core.msg.command.SourceCommand.RemoveReadPoints;
import org.accada.reader.rprm.core.msg.command.SourceCommand.RemoveReadTriggers;
import org.accada.reader.rprm.core.msg.command.SourceCommand.RemoveTagSelectors;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetGlimpsedTimeout;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetLostTimeout;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetMaxReadDutyCycle;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetObservedThreshold;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetObservedTimeout;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetReadCyclesPerTrigger;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetReadTimeout;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetSession;
import org.accada.reader.rprm.core.msg.command.SourceCommand.Write;
import org.accada.reader.rprm.core.msg.command.SourceCommand.WriteID;
import org.w3c.dom.Element;


/**
 * <p>Java class for SourceCommand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourceCommand">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="create">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getName" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="isFixed" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="addReadPoints">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="readPoints" type="{urn:epcglobal:rp:xsd:1}ReadPointListParamType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="removeReadPoints">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="readPoints" type="{urn:epcglobal:rp:xsd:1}ReadPointListParamType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="removeAllReadPoints" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getReadPoint">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getAllReadPoints" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="addReadTriggers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="triggers" type="{urn:epcglobal:rp:xsd:1}TriggerListParamType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="removeReadTriggers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="triggers" type="{urn:epcglobal:rp:xsd:1}TriggerListParamType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="removeAllReadTriggers" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getReadTrigger">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getAllReadTriggers" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="addTagSelectors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="removeTagSelectors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="removeAllTagSelectors" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getTagSelector">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getAllTagSelectors" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getGlimpsedTimeout" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="setGlimpsedTimeout">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getObservedThreshold" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="setObservedThreshold">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getObservedTimeout" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="setObservedTimeout">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getLostTimeout" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="setLostTimeout">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rawReadIDs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorParamType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="readIDs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorParamType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="read">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorParamType"/>
 *                   &lt;element name="passwords" type="{urn:epcglobal:rp:xsd:1}HexStringListType" minOccurs="0"/>
 *                   &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="writeID">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
 *                   &lt;element name="passwords" type="{urn:epcglobal:rp:xsd:1}HexStringListType" minOccurs="0"/>
 *                   &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="write">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="data" type="{urn:epcglobal:rp:xsd:1}TagFieldValueListParamType"/>
 *                   &lt;element name="passwords" type="{urn:epcglobal:rp:xsd:1}HexStringListType" minOccurs="0"/>
 *                   &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="kill">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="passwords" type="{urn:epcglobal:rp:xsd:1}HexStringListType" minOccurs="0"/>
 *                   &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getReadCyclesPerTrigger" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="setReadCyclesPerTrigger">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cycles" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getMaxReadDutyCycle" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="setMaxReadDutyCycle">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dutyCycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getReadTimeout" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="setReadTimeout">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getSession" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="setSession">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="session" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "SourceCommand", propOrder = {
    "create",
    "getName",
    "isFixed",
    "addReadPoints",
    "removeReadPoints",
    "removeAllReadPoints",
    "getReadPoint",
    "getAllReadPoints",
    "addReadTriggers",
    "removeReadTriggers",
    "removeAllReadTriggers",
    "getReadTrigger",
    "getAllReadTriggers",
    "addTagSelectors",
    "removeTagSelectors",
    "removeAllTagSelectors",
    "getTagSelector",
    "getAllTagSelectors",
    "getGlimpsedTimeout",
    "setGlimpsedTimeout",
    "getObservedThreshold",
    "setObservedThreshold",
    "getObservedTimeout",
    "setObservedTimeout",
    "getLostTimeout",
    "setLostTimeout",
    "rawReadIDs",
    "readIDs",
    "read",
    "writeID",
    "write",
    "kill",
    "getReadCyclesPerTrigger",
    "setReadCyclesPerTrigger",
    "getMaxReadDutyCycle",
    "setMaxReadDutyCycle",
    "getReadTimeout",
    "setReadTimeout",
    "getSession",
    "setSession",
    "any"
})
public class SourceCommand {

    protected Create create;
    protected NoParamType getName;
    protected NoParamType isFixed;
    protected AddReadPoints addReadPoints;
    protected RemoveReadPoints removeReadPoints;
    protected NoParamType removeAllReadPoints;
    protected GetReadPoint getReadPoint;
    protected NoParamType getAllReadPoints;
    protected AddReadTriggers addReadTriggers;
    protected RemoveReadTriggers removeReadTriggers;
    protected NoParamType removeAllReadTriggers;
    protected GetReadTrigger getReadTrigger;
    protected NoParamType getAllReadTriggers;
    protected AddTagSelectors addTagSelectors;
    protected RemoveTagSelectors removeTagSelectors;
    protected NoParamType removeAllTagSelectors;
    protected GetTagSelector getTagSelector;
    protected NoParamType getAllTagSelectors;
    protected NoParamType getGlimpsedTimeout;
    protected SetGlimpsedTimeout setGlimpsedTimeout;
    protected NoParamType getObservedThreshold;
    protected SetObservedThreshold setObservedThreshold;
    protected NoParamType getObservedTimeout;
    protected SetObservedTimeout setObservedTimeout;
    protected NoParamType getLostTimeout;
    protected SetLostTimeout setLostTimeout;
    protected RawReadIDs rawReadIDs;
    protected ReadIDs readIDs;
    protected Read read;
    protected WriteID writeID;
    protected Write write;
    protected Kill kill;
    protected NoParamType getReadCyclesPerTrigger;
    protected SetReadCyclesPerTrigger setReadCyclesPerTrigger;
    protected NoParamType getMaxReadDutyCycle;
    protected SetMaxReadDutyCycle setMaxReadDutyCycle;
    protected NoParamType getReadTimeout;
    protected SetReadTimeout setReadTimeout;
    protected NoParamType getSession;
    protected SetSession setSession;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the create property.
     * 
     * @return
     *     possible object is
     *     {@link Create }
     *     
     */
    public Create getCreate() {
        return create;
    }

    /**
     * Sets the value of the create property.
     * 
     * @param value
     *     allowed object is
     *     {@link Create }
     *     
     */
    public void setCreate(Create value) {
        this.create = value;
    }

    /**
     * Gets the value of the getName property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetName() {
        return getName;
    }

    /**
     * Sets the value of the getName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetName(NoParamType value) {
        this.getName = value;
    }

    /**
     * Gets the value of the isFixed property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getIsFixed() {
        return isFixed;
    }

    /**
     * Sets the value of the isFixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setIsFixed(NoParamType value) {
        this.isFixed = value;
    }

    /**
     * Gets the value of the addReadPoints property.
     * 
     * @return
     *     possible object is
     *     {@link AddReadPoints }
     *     
     */
    public AddReadPoints getAddReadPoints() {
        return addReadPoints;
    }

    /**
     * Sets the value of the addReadPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddReadPoints }
     *     
     */
    public void setAddReadPoints(AddReadPoints value) {
        this.addReadPoints = value;
    }

    /**
     * Gets the value of the removeReadPoints property.
     * 
     * @return
     *     possible object is
     *     {@link RemoveReadPoints }
     *     
     */
    public RemoveReadPoints getRemoveReadPoints() {
        return removeReadPoints;
    }

    /**
     * Sets the value of the removeReadPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoveReadPoints }
     *     
     */
    public void setRemoveReadPoints(RemoveReadPoints value) {
        this.removeReadPoints = value;
    }

    /**
     * Gets the value of the removeAllReadPoints property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllReadPoints() {
        return removeAllReadPoints;
    }

    /**
     * Sets the value of the removeAllReadPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllReadPoints(NoParamType value) {
        this.removeAllReadPoints = value;
    }

    /**
     * Gets the value of the getReadPoint property.
     * 
     * @return
     *     possible object is
     *     {@link GetReadPoint }
     *     
     */
    public GetReadPoint getGetReadPoint() {
        return getReadPoint;
    }

    /**
     * Sets the value of the getReadPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetReadPoint }
     *     
     */
    public void setGetReadPoint(GetReadPoint value) {
        this.getReadPoint = value;
    }

    /**
     * Gets the value of the getAllReadPoints property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetAllReadPoints() {
        return getAllReadPoints;
    }

    /**
     * Sets the value of the getAllReadPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetAllReadPoints(NoParamType value) {
        this.getAllReadPoints = value;
    }

    /**
     * Gets the value of the addReadTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link AddReadTriggers }
     *     
     */
    public AddReadTriggers getAddReadTriggers() {
        return addReadTriggers;
    }

    /**
     * Sets the value of the addReadTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddReadTriggers }
     *     
     */
    public void setAddReadTriggers(AddReadTriggers value) {
        this.addReadTriggers = value;
    }

    /**
     * Gets the value of the removeReadTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link RemoveReadTriggers }
     *     
     */
    public RemoveReadTriggers getRemoveReadTriggers() {
        return removeReadTriggers;
    }

    /**
     * Sets the value of the removeReadTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoveReadTriggers }
     *     
     */
    public void setRemoveReadTriggers(RemoveReadTriggers value) {
        this.removeReadTriggers = value;
    }

    /**
     * Gets the value of the removeAllReadTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllReadTriggers() {
        return removeAllReadTriggers;
    }

    /**
     * Sets the value of the removeAllReadTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllReadTriggers(NoParamType value) {
        this.removeAllReadTriggers = value;
    }

    /**
     * Gets the value of the getReadTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link GetReadTrigger }
     *     
     */
    public GetReadTrigger getGetReadTrigger() {
        return getReadTrigger;
    }

    /**
     * Sets the value of the getReadTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetReadTrigger }
     *     
     */
    public void setGetReadTrigger(GetReadTrigger value) {
        this.getReadTrigger = value;
    }

    /**
     * Gets the value of the getAllReadTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetAllReadTriggers() {
        return getAllReadTriggers;
    }

    /**
     * Sets the value of the getAllReadTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetAllReadTriggers(NoParamType value) {
        this.getAllReadTriggers = value;
    }

    /**
     * Gets the value of the addTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link AddTagSelectors }
     *     
     */
    public AddTagSelectors getAddTagSelectors() {
        return addTagSelectors;
    }

    /**
     * Sets the value of the addTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddTagSelectors }
     *     
     */
    public void setAddTagSelectors(AddTagSelectors value) {
        this.addTagSelectors = value;
    }

    /**
     * Gets the value of the removeTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link RemoveTagSelectors }
     *     
     */
    public RemoveTagSelectors getRemoveTagSelectors() {
        return removeTagSelectors;
    }

    /**
     * Sets the value of the removeTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoveTagSelectors }
     *     
     */
    public void setRemoveTagSelectors(RemoveTagSelectors value) {
        this.removeTagSelectors = value;
    }

    /**
     * Gets the value of the removeAllTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllTagSelectors() {
        return removeAllTagSelectors;
    }

    /**
     * Sets the value of the removeAllTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllTagSelectors(NoParamType value) {
        this.removeAllTagSelectors = value;
    }

    /**
     * Gets the value of the getTagSelector property.
     * 
     * @return
     *     possible object is
     *     {@link GetTagSelector }
     *     
     */
    public GetTagSelector getGetTagSelector() {
        return getTagSelector;
    }

    /**
     * Sets the value of the getTagSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetTagSelector }
     *     
     */
    public void setGetTagSelector(GetTagSelector value) {
        this.getTagSelector = value;
    }

    /**
     * Gets the value of the getAllTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetAllTagSelectors() {
        return getAllTagSelectors;
    }

    /**
     * Sets the value of the getAllTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetAllTagSelectors(NoParamType value) {
        this.getAllTagSelectors = value;
    }

    /**
     * Gets the value of the getGlimpsedTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetGlimpsedTimeout() {
        return getGlimpsedTimeout;
    }

    /**
     * Sets the value of the getGlimpsedTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetGlimpsedTimeout(NoParamType value) {
        this.getGlimpsedTimeout = value;
    }

    /**
     * Gets the value of the setGlimpsedTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link SetGlimpsedTimeout }
     *     
     */
    public SetGlimpsedTimeout getSetGlimpsedTimeout() {
        return setGlimpsedTimeout;
    }

    /**
     * Sets the value of the setGlimpsedTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetGlimpsedTimeout }
     *     
     */
    public void setSetGlimpsedTimeout(SetGlimpsedTimeout value) {
        this.setGlimpsedTimeout = value;
    }

    /**
     * Gets the value of the getObservedThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetObservedThreshold() {
        return getObservedThreshold;
    }

    /**
     * Sets the value of the getObservedThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetObservedThreshold(NoParamType value) {
        this.getObservedThreshold = value;
    }

    /**
     * Gets the value of the setObservedThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link SetObservedThreshold }
     *     
     */
    public SetObservedThreshold getSetObservedThreshold() {
        return setObservedThreshold;
    }

    /**
     * Sets the value of the setObservedThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetObservedThreshold }
     *     
     */
    public void setSetObservedThreshold(SetObservedThreshold value) {
        this.setObservedThreshold = value;
    }

    /**
     * Gets the value of the getObservedTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetObservedTimeout() {
        return getObservedTimeout;
    }

    /**
     * Sets the value of the getObservedTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetObservedTimeout(NoParamType value) {
        this.getObservedTimeout = value;
    }

    /**
     * Gets the value of the setObservedTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link SetObservedTimeout }
     *     
     */
    public SetObservedTimeout getSetObservedTimeout() {
        return setObservedTimeout;
    }

    /**
     * Sets the value of the setObservedTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetObservedTimeout }
     *     
     */
    public void setSetObservedTimeout(SetObservedTimeout value) {
        this.setObservedTimeout = value;
    }

    /**
     * Gets the value of the getLostTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetLostTimeout() {
        return getLostTimeout;
    }

    /**
     * Sets the value of the getLostTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetLostTimeout(NoParamType value) {
        this.getLostTimeout = value;
    }

    /**
     * Gets the value of the setLostTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link SetLostTimeout }
     *     
     */
    public SetLostTimeout getSetLostTimeout() {
        return setLostTimeout;
    }

    /**
     * Sets the value of the setLostTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetLostTimeout }
     *     
     */
    public void setSetLostTimeout(SetLostTimeout value) {
        this.setLostTimeout = value;
    }

    /**
     * Gets the value of the rawReadIDs property.
     * 
     * @return
     *     possible object is
     *     {@link RawReadIDs }
     *     
     */
    public RawReadIDs getRawReadIDs() {
        return rawReadIDs;
    }

    /**
     * Sets the value of the rawReadIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RawReadIDs }
     *     
     */
    public void setRawReadIDs(RawReadIDs value) {
        this.rawReadIDs = value;
    }

    /**
     * Gets the value of the readIDs property.
     * 
     * @return
     *     possible object is
     *     {@link ReadIDs }
     *     
     */
    public ReadIDs getReadIDs() {
        return readIDs;
    }

    /**
     * Sets the value of the readIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadIDs }
     *     
     */
    public void setReadIDs(ReadIDs value) {
        this.readIDs = value;
    }

    /**
     * Gets the value of the read property.
     * 
     * @return
     *     possible object is
     *     {@link Read }
     *     
     */
    public Read getRead() {
        return read;
    }

    /**
     * Sets the value of the read property.
     * 
     * @param value
     *     allowed object is
     *     {@link Read }
     *     
     */
    public void setRead(Read value) {
        this.read = value;
    }

    /**
     * Gets the value of the writeID property.
     * 
     * @return
     *     possible object is
     *     {@link WriteID }
     *     
     */
    public WriteID getWriteID() {
        return writeID;
    }

    /**
     * Sets the value of the writeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link WriteID }
     *     
     */
    public void setWriteID(WriteID value) {
        this.writeID = value;
    }

    /**
     * Gets the value of the write property.
     * 
     * @return
     *     possible object is
     *     {@link Write }
     *     
     */
    public Write getWrite() {
        return write;
    }

    /**
     * Sets the value of the write property.
     * 
     * @param value
     *     allowed object is
     *     {@link Write }
     *     
     */
    public void setWrite(Write value) {
        this.write = value;
    }

    /**
     * Gets the value of the kill property.
     * 
     * @return
     *     possible object is
     *     {@link Kill }
     *     
     */
    public Kill getKill() {
        return kill;
    }

    /**
     * Sets the value of the kill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kill }
     *     
     */
    public void setKill(Kill value) {
        this.kill = value;
    }

    /**
     * Gets the value of the getReadCyclesPerTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetReadCyclesPerTrigger() {
        return getReadCyclesPerTrigger;
    }

    /**
     * Sets the value of the getReadCyclesPerTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetReadCyclesPerTrigger(NoParamType value) {
        this.getReadCyclesPerTrigger = value;
    }

    /**
     * Gets the value of the setReadCyclesPerTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link SetReadCyclesPerTrigger }
     *     
     */
    public SetReadCyclesPerTrigger getSetReadCyclesPerTrigger() {
        return setReadCyclesPerTrigger;
    }

    /**
     * Sets the value of the setReadCyclesPerTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetReadCyclesPerTrigger }
     *     
     */
    public void setSetReadCyclesPerTrigger(SetReadCyclesPerTrigger value) {
        this.setReadCyclesPerTrigger = value;
    }

    /**
     * Gets the value of the getMaxReadDutyCycle property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetMaxReadDutyCycle() {
        return getMaxReadDutyCycle;
    }

    /**
     * Sets the value of the getMaxReadDutyCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetMaxReadDutyCycle(NoParamType value) {
        this.getMaxReadDutyCycle = value;
    }

    /**
     * Gets the value of the setMaxReadDutyCycle property.
     * 
     * @return
     *     possible object is
     *     {@link SetMaxReadDutyCycle }
     *     
     */
    public SetMaxReadDutyCycle getSetMaxReadDutyCycle() {
        return setMaxReadDutyCycle;
    }

    /**
     * Sets the value of the setMaxReadDutyCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetMaxReadDutyCycle }
     *     
     */
    public void setSetMaxReadDutyCycle(SetMaxReadDutyCycle value) {
        this.setMaxReadDutyCycle = value;
    }

    /**
     * Gets the value of the getReadTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetReadTimeout() {
        return getReadTimeout;
    }

    /**
     * Sets the value of the getReadTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetReadTimeout(NoParamType value) {
        this.getReadTimeout = value;
    }

    /**
     * Gets the value of the setReadTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link SetReadTimeout }
     *     
     */
    public SetReadTimeout getSetReadTimeout() {
        return setReadTimeout;
    }

    /**
     * Sets the value of the setReadTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetReadTimeout }
     *     
     */
    public void setSetReadTimeout(SetReadTimeout value) {
        this.setReadTimeout = value;
    }

    /**
     * Gets the value of the getSession property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGetSession() {
        return getSession;
    }

    /**
     * Sets the value of the getSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGetSession(NoParamType value) {
        this.getSession = value;
    }

    /**
     * Gets the value of the setSession property.
     * 
     * @return
     *     possible object is
     *     {@link SetSession }
     *     
     */
    public SetSession getSetSession() {
        return setSession;
    }

    /**
     * Sets the value of the setSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetSession }
     *     
     */
    public void setSetSession(SetSession value) {
        this.setSession = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="readPoints" type="{urn:epcglobal:rp:xsd:1}ReadPointListParamType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "readPoints"
    })
    public static class AddReadPoints {

        protected ReadPointListParamType readPoints;

        /**
         * Gets the value of the readPoints property.
         * 
         * @return
         *     possible object is
         *     {@link ReadPointListParamType }
         *     
         */
        public ReadPointListParamType getReadPoints() {
            return readPoints;
        }

        /**
         * Sets the value of the readPoints property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReadPointListParamType }
         *     
         */
        public void setReadPoints(ReadPointListParamType value) {
            this.readPoints = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="triggers" type="{urn:epcglobal:rp:xsd:1}TriggerListParamType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "triggers"
    })
    public static class AddReadTriggers {

        protected TriggerListParamType triggers;

        /**
         * Gets the value of the triggers property.
         * 
         * @return
         *     possible object is
         *     {@link TriggerListParamType }
         *     
         */
        public TriggerListParamType getTriggers() {
            return triggers;
        }

        /**
         * Sets the value of the triggers property.
         * 
         * @param value
         *     allowed object is
         *     {@link TriggerListParamType }
         *     
         */
        public void setTriggers(TriggerListParamType value) {
            this.triggers = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "selectors"
    })
    public static class AddTagSelectors {

        protected TagSelectorListParamType selectors;

        /**
         * Gets the value of the selectors property.
         * 
         * @return
         *     possible object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public TagSelectorListParamType getSelectors() {
            return selectors;
        }

        /**
         * Sets the value of the selectors property.
         * 
         * @param value
         *     allowed object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public void setSelectors(TagSelectorListParamType value) {
            this.selectors = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name"
    })
    public static class Create {

        protected String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name"
    })
    public static class GetReadPoint {

        protected String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name"
    })
    public static class GetReadTrigger {

        protected String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name"
    })
    public static class GetTagSelector {

        protected String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="passwords" type="{urn:epcglobal:rp:xsd:1}HexStringListType" minOccurs="0"/>
     *         &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "passwords",
        "selectors"
    })
    public static class Kill {

        protected HexStringListType passwords;
        protected TagSelectorListParamType selectors;

        /**
         * Gets the value of the passwords property.
         * 
         * @return
         *     possible object is
         *     {@link HexStringListType }
         *     
         */
        public HexStringListType getPasswords() {
            return passwords;
        }

        /**
         * Sets the value of the passwords property.
         * 
         * @param value
         *     allowed object is
         *     {@link HexStringListType }
         *     
         */
        public void setPasswords(HexStringListType value) {
            this.passwords = value;
        }

        /**
         * Gets the value of the selectors property.
         * 
         * @return
         *     possible object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public TagSelectorListParamType getSelectors() {
            return selectors;
        }

        /**
         * Sets the value of the selectors property.
         * 
         * @param value
         *     allowed object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public void setSelectors(TagSelectorListParamType value) {
            this.selectors = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorParamType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataSelector"
    })
    public static class RawReadIDs {

        protected String dataSelector;

        /**
         * Gets the value of the dataSelector property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataSelector() {
            return dataSelector;
        }

        /**
         * Sets the value of the dataSelector property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataSelector(String value) {
            this.dataSelector = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorParamType"/>
     *         &lt;element name="passwords" type="{urn:epcglobal:rp:xsd:1}HexStringListType" minOccurs="0"/>
     *         &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataSelector",
        "passwords",
        "selectors"
    })
    public static class Read {

        protected String dataSelector;
        protected HexStringListType passwords;
        protected TagSelectorListParamType selectors;

        /**
         * Gets the value of the dataSelector property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataSelector() {
            return dataSelector;
        }

        /**
         * Sets the value of the dataSelector property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataSelector(String value) {
            this.dataSelector = value;
        }

        /**
         * Gets the value of the passwords property.
         * 
         * @return
         *     possible object is
         *     {@link HexStringListType }
         *     
         */
        public HexStringListType getPasswords() {
            return passwords;
        }

        /**
         * Sets the value of the passwords property.
         * 
         * @param value
         *     allowed object is
         *     {@link HexStringListType }
         *     
         */
        public void setPasswords(HexStringListType value) {
            this.passwords = value;
        }

        /**
         * Gets the value of the selectors property.
         * 
         * @return
         *     possible object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public TagSelectorListParamType getSelectors() {
            return selectors;
        }

        /**
         * Sets the value of the selectors property.
         * 
         * @param value
         *     allowed object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public void setSelectors(TagSelectorListParamType value) {
            this.selectors = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorParamType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataSelector"
    })
    public static class ReadIDs {

        protected String dataSelector;

        /**
         * Gets the value of the dataSelector property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataSelector() {
            return dataSelector;
        }

        /**
         * Sets the value of the dataSelector property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataSelector(String value) {
            this.dataSelector = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="readPoints" type="{urn:epcglobal:rp:xsd:1}ReadPointListParamType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "readPoints"
    })
    public static class RemoveReadPoints {

        protected ReadPointListParamType readPoints;

        /**
         * Gets the value of the readPoints property.
         * 
         * @return
         *     possible object is
         *     {@link ReadPointListParamType }
         *     
         */
        public ReadPointListParamType getReadPoints() {
            return readPoints;
        }

        /**
         * Sets the value of the readPoints property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReadPointListParamType }
         *     
         */
        public void setReadPoints(ReadPointListParamType value) {
            this.readPoints = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="triggers" type="{urn:epcglobal:rp:xsd:1}TriggerListParamType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "triggers"
    })
    public static class RemoveReadTriggers {

        protected TriggerListParamType triggers;

        /**
         * Gets the value of the triggers property.
         * 
         * @return
         *     possible object is
         *     {@link TriggerListParamType }
         *     
         */
        public TriggerListParamType getTriggers() {
            return triggers;
        }

        /**
         * Sets the value of the triggers property.
         * 
         * @param value
         *     allowed object is
         *     {@link TriggerListParamType }
         *     
         */
        public void setTriggers(TriggerListParamType value) {
            this.triggers = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "selectors"
    })
    public static class RemoveTagSelectors {

        protected TagSelectorListParamType selectors;

        /**
         * Gets the value of the selectors property.
         * 
         * @return
         *     possible object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public TagSelectorListParamType getSelectors() {
            return selectors;
        }

        /**
         * Sets the value of the selectors property.
         * 
         * @param value
         *     allowed object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public void setSelectors(TagSelectorListParamType value) {
            this.selectors = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timeout"
    })
    public static class SetGlimpsedTimeout {

        @XmlElement(type = Integer.class)
        protected int timeout;

        /**
         * Gets the value of the timeout property.
         * 
         */
        public int getTimeout() {
            return timeout;
        }

        /**
         * Sets the value of the timeout property.
         * 
         */
        public void setTimeout(int value) {
            this.timeout = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timeout"
    })
    public static class SetLostTimeout {

        @XmlElement(type = Integer.class)
        protected int timeout;

        /**
         * Gets the value of the timeout property.
         * 
         */
        public int getTimeout() {
            return timeout;
        }

        /**
         * Sets the value of the timeout property.
         * 
         */
        public void setTimeout(int value) {
            this.timeout = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dutyCycle" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dutyCycle"
    })
    public static class SetMaxReadDutyCycle {

        @XmlElement(type = Integer.class)
        protected int dutyCycle;

        /**
         * Gets the value of the dutyCycle property.
         * 
         */
        public int getDutyCycle() {
            return dutyCycle;
        }

        /**
         * Sets the value of the dutyCycle property.
         * 
         */
        public void setDutyCycle(int value) {
            this.dutyCycle = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "threshold"
    })
    public static class SetObservedThreshold {

        @XmlElement(type = Integer.class)
        protected int threshold;

        /**
         * Gets the value of the threshold property.
         * 
         */
        public int getThreshold() {
            return threshold;
        }

        /**
         * Sets the value of the threshold property.
         * 
         */
        public void setThreshold(int value) {
            this.threshold = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timeout"
    })
    public static class SetObservedTimeout {

        @XmlElement(type = Integer.class)
        protected int timeout;

        /**
         * Gets the value of the timeout property.
         * 
         */
        public int getTimeout() {
            return timeout;
        }

        /**
         * Sets the value of the timeout property.
         * 
         */
        public void setTimeout(int value) {
            this.timeout = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cycles" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cycles"
    })
    public static class SetReadCyclesPerTrigger {

        @XmlElement(type = Integer.class)
        protected int cycles;

        /**
         * Gets the value of the cycles property.
         * 
         */
        public int getCycles() {
            return cycles;
        }

        /**
         * Sets the value of the cycles property.
         * 
         */
        public void setCycles(int value) {
            this.cycles = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timeout"
    })
    public static class SetReadTimeout {

        @XmlElement(type = Integer.class)
        protected int timeout;

        /**
         * Gets the value of the timeout property.
         * 
         */
        public int getTimeout() {
            return timeout;
        }

        /**
         * Sets the value of the timeout property.
         * 
         */
        public void setTimeout(int value) {
            this.timeout = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="session" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "session"
    })
    public static class SetSession {

        @XmlElement(type = Integer.class)
        protected int session;

        /**
         * Gets the value of the session property.
         * 
         */
        public int getSession() {
            return session;
        }

        /**
         * Sets the value of the session property.
         * 
         */
        public void setSession(int value) {
            this.session = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="data" type="{urn:epcglobal:rp:xsd:1}TagFieldValueListParamType"/>
     *         &lt;element name="passwords" type="{urn:epcglobal:rp:xsd:1}HexStringListType" minOccurs="0"/>
     *         &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "data",
        "passwords",
        "selectors"
    })
    public static class Write {

        protected TagFieldValueListParamType data;
        protected HexStringListType passwords;
        protected TagSelectorListParamType selectors;

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link TagFieldValueListParamType }
         *     
         */
        public TagFieldValueListParamType getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link TagFieldValueListParamType }
         *     
         */
        public void setData(TagFieldValueListParamType value) {
            this.data = value;
        }

        /**
         * Gets the value of the passwords property.
         * 
         * @return
         *     possible object is
         *     {@link HexStringListType }
         *     
         */
        public HexStringListType getPasswords() {
            return passwords;
        }

        /**
         * Sets the value of the passwords property.
         * 
         * @param value
         *     allowed object is
         *     {@link HexStringListType }
         *     
         */
        public void setPasswords(HexStringListType value) {
            this.passwords = value;
        }

        /**
         * Gets the value of the selectors property.
         * 
         * @return
         *     possible object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public TagSelectorListParamType getSelectors() {
            return selectors;
        }

        /**
         * Sets the value of the selectors property.
         * 
         * @param value
         *     allowed object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public void setSelectors(TagSelectorListParamType value) {
            this.selectors = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
     *         &lt;element name="passwords" type="{urn:epcglobal:rp:xsd:1}HexStringListType" minOccurs="0"/>
     *         &lt;element name="selectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListParamType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "passwords",
        "selectors"
    })
    public static class WriteID {

        @XmlElement(type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        protected byte[] id;
        protected HexStringListType passwords;
        protected TagSelectorListParamType selectors;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(byte[] value) {
            this.id = ((byte[]) value);
        }

        /**
         * Gets the value of the passwords property.
         * 
         * @return
         *     possible object is
         *     {@link HexStringListType }
         *     
         */
        public HexStringListType getPasswords() {
            return passwords;
        }

        /**
         * Sets the value of the passwords property.
         * 
         * @param value
         *     allowed object is
         *     {@link HexStringListType }
         *     
         */
        public void setPasswords(HexStringListType value) {
            this.passwords = value;
        }

        /**
         * Gets the value of the selectors property.
         * 
         * @return
         *     possible object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public TagSelectorListParamType getSelectors() {
            return selectors;
        }

        /**
         * Sets the value of the selectors property.
         * 
         * @param value
         *     allowed object is
         *     {@link TagSelectorListParamType }
         *     
         */
        public void setSelectors(TagSelectorListParamType value) {
            this.selectors = value;
        }

    }

}
