/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Accada (www.accada.org).
 *
 * Accada is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Accada is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Accada; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.05 at 05:03:34 PM CEST 
//


package org.accada.reader.rprm.core.msg.command;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

import org.accada.reader.rprm.core.msg.command.AddressReturnType;
import org.accada.reader.rprm.core.msg.command.BooleanReturnType;
import org.accada.reader.rprm.core.msg.command.Command;
import org.accada.reader.rprm.core.msg.command.DataSelectorCommand;
import org.accada.reader.rprm.core.msg.command.DataSelectorListParamType;
import org.accada.reader.rprm.core.msg.command.DataSelectorListReturnType;
import org.accada.reader.rprm.core.msg.command.DataSelectorReturnType;
import org.accada.reader.rprm.core.msg.command.EPC;
import org.accada.reader.rprm.core.msg.command.EpcReturnType;
import org.accada.reader.rprm.core.msg.command.EventTimeType;
import org.accada.reader.rprm.core.msg.command.EventTypeCommand;
import org.accada.reader.rprm.core.msg.command.EventTypeListParamType;
import org.accada.reader.rprm.core.msg.command.EventTypeListReturnValue;
import org.accada.reader.rprm.core.msg.command.FieldNameCommand;
import org.accada.reader.rprm.core.msg.command.FieldNameListParamType;
import org.accada.reader.rprm.core.msg.command.FieldNameListReturnType;
import org.accada.reader.rprm.core.msg.command.HexStringListType;
import org.accada.reader.rprm.core.msg.command.HexStringReturnType;
import org.accada.reader.rprm.core.msg.command.IntReturnType;
import org.accada.reader.rprm.core.msg.command.NoParamType;
import org.accada.reader.rprm.core.msg.command.NotificationChannelCommand;
import org.accada.reader.rprm.core.msg.command.NotificationChannelListParamType;
import org.accada.reader.rprm.core.msg.command.NotificationChannelListReturnType;
import org.accada.reader.rprm.core.msg.command.NotificationChannelReturnType;
import org.accada.reader.rprm.core.msg.command.ObjectFactory;
import org.accada.reader.rprm.core.msg.command.ReadPointCommand;
import org.accada.reader.rprm.core.msg.command.ReadPointListParamType;
import org.accada.reader.rprm.core.msg.command.ReadPointListReturnType;
import org.accada.reader.rprm.core.msg.command.ReadPointReturnType;
import org.accada.reader.rprm.core.msg.command.ReadReportType;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand;
import org.accada.reader.rprm.core.msg.command.ReaderTimeType;
import org.accada.reader.rprm.core.msg.command.SourceCommand;
import org.accada.reader.rprm.core.msg.command.SourceInfoType;
import org.accada.reader.rprm.core.msg.command.SourceListParamType;
import org.accada.reader.rprm.core.msg.command.SourceListReturnType;
import org.accada.reader.rprm.core.msg.command.SourceReturnType;
import org.accada.reader.rprm.core.msg.command.StringListParamType;
import org.accada.reader.rprm.core.msg.command.StringListReturnType;
import org.accada.reader.rprm.core.msg.command.StringReturnType;
import org.accada.reader.rprm.core.msg.command.TagEventType;
import org.accada.reader.rprm.core.msg.command.TagFieldCommand;
import org.accada.reader.rprm.core.msg.command.TagFieldListParamType;
import org.accada.reader.rprm.core.msg.command.TagFieldListReturnType;
import org.accada.reader.rprm.core.msg.command.TagFieldReturnType;
import org.accada.reader.rprm.core.msg.command.TagFieldValueListParamType;
import org.accada.reader.rprm.core.msg.command.TagFieldValueParamType;
import org.accada.reader.rprm.core.msg.command.TagSelectorCommand;
import org.accada.reader.rprm.core.msg.command.TagSelectorListParamType;
import org.accada.reader.rprm.core.msg.command.TagSelectorListReturnType;
import org.accada.reader.rprm.core.msg.command.TagSelectorReturnType;
import org.accada.reader.rprm.core.msg.command.TagType;
import org.accada.reader.rprm.core.msg.command.TimeStampReturnType;
import org.accada.reader.rprm.core.msg.command.TriggerCommand;
import org.accada.reader.rprm.core.msg.command.TriggerListParamType;
import org.accada.reader.rprm.core.msg.command.TriggerListReturnType;
import org.accada.reader.rprm.core.msg.command.TriggerReturnType;
import org.accada.reader.rprm.core.msg.command.TriggerTypeCommand;
import org.accada.reader.rprm.core.msg.command.TriggerTypeListReturnType;
import org.accada.reader.rprm.core.msg.command.TriggerTypeReturnType;
import org.accada.reader.rprm.core.msg.command.TriggerValueReturnType;
import org.accada.reader.rprm.core.msg.command.DataSelectorCommand.AddEventFilters;
import org.accada.reader.rprm.core.msg.command.DataSelectorCommand.AddFieldNames;
import org.accada.reader.rprm.core.msg.command.DataSelectorCommand.AddTagFieldNames;
import org.accada.reader.rprm.core.msg.command.DataSelectorCommand.RemoveEventFilters;
import org.accada.reader.rprm.core.msg.command.DataSelectorCommand.RemoveFieldNames;
import org.accada.reader.rprm.core.msg.command.DataSelectorCommand.RemoveTagFieldNames;
import org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.AddNotificationTriggers;
import org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.AddSources;
import org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.GetNotificationTrigger;
import org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.ReadQueuedData;
import org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.RemoveNotificationTriggers;
import org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.SetAddress;
import org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.SetDataSelector;
import org.accada.reader.rprm.core.msg.command.ReadReportType.SourceReport;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetDataSelector;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetNotificationChannel;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetTagField;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetTrigger;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveDataSelectors;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveNotificationChannels;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveTagFields;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveTriggers;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.SetCurrentDataSelector;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.SetCurrentSource;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.SetHandle;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.SetName;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.SetRole;
import org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.SetTimeUTC;
import org.accada.reader.rprm.core.msg.command.SourceCommand.AddReadPoints;
import org.accada.reader.rprm.core.msg.command.SourceCommand.AddReadTriggers;
import org.accada.reader.rprm.core.msg.command.SourceCommand.AddTagSelectors;
import org.accada.reader.rprm.core.msg.command.SourceCommand.GetReadTrigger;
import org.accada.reader.rprm.core.msg.command.SourceCommand.Kill;
import org.accada.reader.rprm.core.msg.command.SourceCommand.RawReadIDs;
import org.accada.reader.rprm.core.msg.command.SourceCommand.Read;
import org.accada.reader.rprm.core.msg.command.SourceCommand.ReadIDs;
import org.accada.reader.rprm.core.msg.command.SourceCommand.RemoveReadPoints;
import org.accada.reader.rprm.core.msg.command.SourceCommand.RemoveReadTriggers;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetGlimpsedTimeout;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetLostTimeout;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetMaxReadDutyCycle;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetObservedThreshold;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetObservedTimeout;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetReadCyclesPerTrigger;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetReadTimeout;
import org.accada.reader.rprm.core.msg.command.SourceCommand.SetSession;
import org.accada.reader.rprm.core.msg.command.SourceCommand.Write;
import org.accada.reader.rprm.core.msg.command.SourceCommand.WriteID;
import org.accada.reader.rprm.core.msg.command.TagEventType.EventTriggers;
import org.accada.reader.rprm.core.msg.command.TagFieldCommand.SetLength;
import org.accada.reader.rprm.core.msg.command.TagFieldCommand.SetMemoryBank;
import org.accada.reader.rprm.core.msg.command.TagFieldCommand.SetOffset;
import org.accada.reader.rprm.core.msg.command.TagFieldCommand.SetTagFieldName;
import org.accada.reader.rprm.core.msg.command.TriggerTypeListReturnType.ReturnValue;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.accada.reader.msg.command package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HexStringListTypeListValue_QNAME = new QName("", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.accada.reader.msg.command
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link AddNotificationTriggers }
     * 
     */
    public AddNotificationTriggers createNotificationChannelCommandAddNotificationTriggers() {
        return new AddNotificationTriggers();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.GetSource }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.GetSource createNotificationChannelCommandGetSource() {
        return new org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.GetSource();
    }

    /**
     * Create an instance of {@link RemoveDataSelectors }
     * 
     */
    public RemoveDataSelectors createReaderDeviceCommandRemoveDataSelectors() {
        return new RemoveDataSelectors();
    }

    /**
     * Create an instance of {@link TriggerCommand }
     * 
     */
    public TriggerCommand createTriggerCommand() {
        return new TriggerCommand();
    }

    /**
     * Create an instance of {@link WriteID }
     * 
     */
    public WriteID createSourceCommandWriteID() {
        return new WriteID();
    }

    /**
     * Create an instance of {@link AddTagSelectors }
     * 
     */
    public AddTagSelectors createSourceCommandAddTagSelectors() {
        return new AddTagSelectors();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.DataSelectorListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.DataSelectorListParamType.List createDataSelectorListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.DataSelectorListParamType.List();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.FieldNameListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.FieldNameListParamType.List createFieldNameListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.FieldNameListParamType.List();
    }

    /**
     * Create an instance of {@link SetReadTimeout }
     * 
     */
    public SetReadTimeout createSourceCommandSetReadTimeout() {
        return new SetReadTimeout();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.TagFieldCommand.Create }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.TagFieldCommand.Create createTagFieldCommandCreate() {
        return new org.accada.reader.rprm.core.msg.command.TagFieldCommand.Create();
    }

    /**
     * Create an instance of {@link Write }
     * 
     */
    public Write createSourceCommandWrite() {
        return new Write();
    }

    /**
     * Create an instance of {@link ReadPointReturnType }
     * 
     */
    public ReadPointReturnType createReadPointReturnType() {
        return new ReadPointReturnType();
    }

    /**
     * Create an instance of {@link SetMaxReadDutyCycle }
     * 
     */
    public SetMaxReadDutyCycle createSourceCommandSetMaxReadDutyCycle() {
        return new SetMaxReadDutyCycle();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.TagFieldValueListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.TagFieldValueListParamType.List createTagFieldValueListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.TagFieldValueListParamType.List();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.TagSelectorListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.TagSelectorListParamType.List createTagSelectorListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.TagSelectorListParamType.List();
    }

    /**
     * Create an instance of {@link SourceListReturnType }
     * 
     */
    public SourceListReturnType createSourceListReturnType() {
        return new SourceListReturnType();
    }

    /**
     * Create an instance of {@link NotificationChannelReturnType }
     * 
     */
    public NotificationChannelReturnType createNotificationChannelReturnType() {
        return new NotificationChannelReturnType();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.RemoveSources }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.RemoveSources createNotificationChannelCommandRemoveSources() {
        return new org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.RemoveSources();
    }

    /**
     * Create an instance of {@link AddEventFilters }
     * 
     */
    public AddEventFilters createDataSelectorCommandAddEventFilters() {
        return new AddEventFilters();
    }

    /**
     * Create an instance of {@link TagFieldListParamType }
     * 
     */
    public TagFieldListParamType createTagFieldListParamType() {
        return new TagFieldListParamType();
    }

    /**
     * Create an instance of {@link NotificationChannelCommand }
     * 
     */
    public NotificationChannelCommand createNotificationChannelCommand() {
        return new NotificationChannelCommand();
    }

    /**
     * Create an instance of {@link ReaderTimeType }
     * 
     */
    public ReaderTimeType createReaderTimeType() {
        return new ReaderTimeType();
    }

    /**
     * Create an instance of {@link GetNotificationTrigger }
     * 
     */
    public GetNotificationTrigger createNotificationChannelCommandGetNotificationTrigger() {
        return new GetNotificationTrigger();
    }

    /**
     * Create an instance of {@link StringListParamType }
     * 
     */
    public StringListParamType createStringListParamType() {
        return new StringListParamType();
    }

    /**
     * Create an instance of {@link SetCurrentDataSelector }
     * 
     */
    public SetCurrentDataSelector createReaderDeviceCommandSetCurrentDataSelector() {
        return new SetCurrentDataSelector();
    }

    /**
     * Create an instance of {@link TagFieldListReturnType }
     * 
     */
    public TagFieldListReturnType createTagFieldListReturnType() {
        return new TagFieldListReturnType();
    }

    /**
     * Create an instance of {@link NotificationChannelListReturnType }
     * 
     */
    public NotificationChannelListReturnType createNotificationChannelListReturnType() {
        return new NotificationChannelListReturnType();
    }

    /**
     * Create an instance of {@link SetSession }
     * 
     */
    public SetSession createSourceCommandSetSession() {
        return new SetSession();
    }

    /**
     * Create an instance of {@link TagSelectorReturnType }
     * 
     */
    public TagSelectorReturnType createTagSelectorReturnType() {
        return new TagSelectorReturnType();
    }

    /**
     * Create an instance of {@link FieldNameListReturnType }
     * 
     */
    public FieldNameListReturnType createFieldNameListReturnType() {
        return new FieldNameListReturnType();
    }

    /**
     * Create an instance of {@link RemoveReadPoints }
     * 
     */
    public RemoveReadPoints createSourceCommandRemoveReadPoints() {
        return new RemoveReadPoints();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetReadPoint }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetReadPoint createReaderDeviceCommandGetReadPoint() {
        return new org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetReadPoint();
    }

    /**
     * Create an instance of {@link SetLength }
     * 
     */
    public SetLength createTagFieldCommandSetLength() {
        return new SetLength();
    }

    /**
     * Create an instance of {@link BooleanReturnType }
     * 
     */
    public BooleanReturnType createBooleanReturnType() {
        return new BooleanReturnType();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.TriggerCommand.Create }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.TriggerCommand.Create createTriggerCommandCreate() {
        return new org.accada.reader.rprm.core.msg.command.TriggerCommand.Create();
    }

    /**
     * Create an instance of {@link TagFieldReturnType }
     * 
     */
    public TagFieldReturnType createTagFieldReturnType() {
        return new TagFieldReturnType();
    }

    /**
     * Create an instance of {@link TriggerValueReturnType }
     * 
     */
    public TriggerValueReturnType createTriggerValueReturnType() {
        return new TriggerValueReturnType();
    }

    /**
     * Create an instance of {@link TriggerReturnType }
     * 
     */
    public TriggerReturnType createTriggerReturnType() {
        return new TriggerReturnType();
    }

    /**
     * Create an instance of {@link RawReadIDs }
     * 
     */
    public RawReadIDs createSourceCommandRawReadIDs() {
        return new RawReadIDs();
    }

    /**
     * Create an instance of {@link EventTimeType }
     * 
     */
    public EventTimeType createEventTimeType() {
        return new EventTimeType();
    }

    /**
     * Create an instance of {@link SetGlimpsedTimeout }
     * 
     */
    public SetGlimpsedTimeout createSourceCommandSetGlimpsedTimeout() {
        return new SetGlimpsedTimeout();
    }

    /**
     * Create an instance of {@link NotificationChannelListParamType }
     * 
     */
    public NotificationChannelListParamType createNotificationChannelListParamType() {
        return new NotificationChannelListParamType();
    }

    /**
     * Create an instance of {@link SetHandle }
     * 
     */
    public SetHandle createReaderDeviceCommandSetHandle() {
        return new SetHandle();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.SourceCommand.RemoveTagSelectors }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.SourceCommand.RemoveTagSelectors createSourceCommandRemoveTagSelectors() {
        return new org.accada.reader.rprm.core.msg.command.SourceCommand.RemoveTagSelectors();
    }

    /**
     * Create an instance of {@link GetNotificationChannel }
     * 
     */
    public GetNotificationChannel createReaderDeviceCommandGetNotificationChannel() {
        return new GetNotificationChannel();
    }

    /**
     * Create an instance of {@link FieldNameCommand }
     * 
     */
    public FieldNameCommand createFieldNameCommand() {
        return new FieldNameCommand();
    }

    /**
     * Create an instance of {@link ReadQueuedData }
     * 
     */
    public ReadQueuedData createNotificationChannelCommandReadQueuedData() {
        return new ReadQueuedData();
    }

    /**
     * Create an instance of {@link TriggerListParamType }
     * 
     */
    public TriggerListParamType createTriggerListParamType() {
        return new TriggerListParamType();
    }

    /**
     * Create an instance of {@link ReadPointListReturnType }
     * 
     */
    public ReadPointListReturnType createReadPointListReturnType() {
        return new ReadPointListReturnType();
    }

    /**
     * Create an instance of {@link StringListReturnType }
     * 
     */
    public StringListReturnType createStringListReturnType() {
        return new StringListReturnType();
    }

    /**
     * Create an instance of {@link GetDataSelector }
     * 
     */
    public GetDataSelector createReaderDeviceCommandGetDataSelector() {
        return new GetDataSelector();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetSource }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetSource createReaderDeviceCommandGetSource() {
        return new org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetSource();
    }

    /**
     * Create an instance of {@link GetTagField }
     * 
     */
    public GetTagField createReaderDeviceCommandGetTagField() {
        return new GetTagField();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.TriggerListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.TriggerListParamType.List createTriggerListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.TriggerListParamType.List();
    }

    /**
     * Create an instance of {@link AddTagFieldNames }
     * 
     */
    public AddTagFieldNames createDataSelectorCommandAddTagFieldNames() {
        return new AddTagFieldNames();
    }

    /**
     * Create an instance of {@link DataSelectorListReturnType }
     * 
     */
    public DataSelectorListReturnType createDataSelectorListReturnType() {
        return new DataSelectorListReturnType();
    }

    /**
     * Create an instance of {@link TagFieldValueParamType }
     * 
     */
    public TagFieldValueParamType createTagFieldValueParamType() {
        return new TagFieldValueParamType();
    }

    /**
     * Create an instance of {@link NoParamType }
     * 
     */
    public NoParamType createNoParamType() {
        return new NoParamType();
    }

    /**
     * Create an instance of {@link DataSelectorCommand }
     * 
     */
    public DataSelectorCommand createDataSelectorCommand() {
        return new DataSelectorCommand();
    }

    /**
     * Create an instance of {@link GetTrigger }
     * 
     */
    public GetTrigger createReaderDeviceCommandGetTrigger() {
        return new GetTrigger();
    }

    /**
     * Create an instance of {@link SetAddress }
     * 
     */
    public SetAddress createNotificationChannelCommandSetAddress() {
        return new SetAddress();
    }

    /**
     * Create an instance of {@link TriggerTypeReturnType }
     * 
     */
    public TriggerTypeReturnType createTriggerTypeReturnType() {
        return new TriggerTypeReturnType();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.Create }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.Create createNotificationChannelCommandCreate() {
        return new org.accada.reader.rprm.core.msg.command.NotificationChannelCommand.Create();
    }

    /**
     * Create an instance of {@link StringReturnType }
     * 
     */
    public StringReturnType createStringReturnType() {
        return new StringReturnType();
    }

    /**
     * Create an instance of {@link TagFieldValueListParamType }
     * 
     */
    public TagFieldValueListParamType createTagFieldValueListParamType() {
        return new TagFieldValueListParamType();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveSources }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveSources createReaderDeviceCommandRemoveSources() {
        return new org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveSources();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetTagSelector }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetTagSelector createReaderDeviceCommandGetTagSelector() {
        return new org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.GetTagSelector();
    }

    /**
     * Create an instance of {@link SetCurrentSource }
     * 
     */
    public SetCurrentSource createReaderDeviceCommandSetCurrentSource() {
        return new SetCurrentSource();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveTagSelectors }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveTagSelectors createReaderDeviceCommandRemoveTagSelectors() {
        return new org.accada.reader.rprm.core.msg.command.ReaderDeviceCommand.RemoveTagSelectors();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.TriggerTypeListReturnType.ReturnValue.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.TriggerTypeListReturnType.ReturnValue.List createTriggerTypeListReturnTypeReturnValueList() {
        return new org.accada.reader.rprm.core.msg.command.TriggerTypeListReturnType.ReturnValue.List();
    }

    /**
     * Create an instance of {@link EPC }
     * 
     */
    public EPC createEPC() {
        return new EPC();
    }

    /**
     * Create an instance of {@link TagFieldCommand }
     * 
     */
    public TagFieldCommand createTagFieldCommand() {
        return new TagFieldCommand();
    }

    /**
     * Create an instance of {@link SourceCommand }
     * 
     */
    public SourceCommand createSourceCommand() {
        return new SourceCommand();
    }

    /**
     * Create an instance of {@link TagSelectorListReturnType }
     * 
     */
    public TagSelectorListReturnType createTagSelectorListReturnType() {
        return new TagSelectorListReturnType();
    }

    /**
     * Create an instance of {@link SourceInfoType }
     * 
     */
    public SourceInfoType createSourceInfoType() {
        return new SourceInfoType();
    }

    /**
     * Create an instance of {@link AddReadPoints }
     * 
     */
    public AddReadPoints createSourceCommandAddReadPoints() {
        return new AddReadPoints();
    }

    /**
     * Create an instance of {@link RemoveNotificationTriggers }
     * 
     */
    public RemoveNotificationTriggers createNotificationChannelCommandRemoveNotificationTriggers() {
        return new RemoveNotificationTriggers();
    }

    /**
     * Create an instance of {@link EventTriggers }
     * 
     */
    public EventTriggers createTagEventTypeEventTriggers() {
        return new EventTriggers();
    }

    /**
     * Create an instance of {@link DataSelectorListParamType }
     * 
     */
    public DataSelectorListParamType createDataSelectorListParamType() {
        return new DataSelectorListParamType();
    }

    /**
     * Create an instance of {@link GetReadTrigger }
     * 
     */
    public GetReadTrigger createSourceCommandGetReadTrigger() {
        return new GetReadTrigger();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.TagSelectorCommand.Create }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.TagSelectorCommand.Create createTagSelectorCommandCreate() {
        return new org.accada.reader.rprm.core.msg.command.TagSelectorCommand.Create();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.ReadPointListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.ReadPointListParamType.List createReadPointListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.ReadPointListParamType.List();
    }

    /**
     * Create an instance of {@link HexStringReturnType }
     * 
     */
    public HexStringReturnType createHexStringReturnType() {
        return new HexStringReturnType();
    }

    /**
     * Create an instance of {@link ReadIDs }
     * 
     */
    public ReadIDs createSourceCommandReadIDs() {
        return new ReadIDs();
    }

    /**
     * Create an instance of {@link SetOffset }
     * 
     */
    public SetOffset createTagFieldCommandSetOffset() {
        return new SetOffset();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.NotificationChannelListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.NotificationChannelListParamType.List createNotificationChannelListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.NotificationChannelListParamType.List();
    }

    /**
     * Create an instance of {@link RemoveTagFieldNames }
     * 
     */
    public RemoveTagFieldNames createDataSelectorCommandRemoveTagFieldNames() {
        return new RemoveTagFieldNames();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.SourceListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.SourceListParamType.List createSourceListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.SourceListParamType.List();
    }

    /**
     * Create an instance of {@link ReadReportType }
     * 
     */
    public ReadReportType createReadReportType() {
        return new ReadReportType();
    }

    /**
     * Create an instance of {@link TagEventType }
     * 
     */
    public TagEventType createTagEventType() {
        return new TagEventType();
    }

    /**
     * Create an instance of {@link ReadPointCommand }
     * 
     */
    public ReadPointCommand createReadPointCommand() {
        return new ReadPointCommand();
    }

    /**
     * Create an instance of {@link SetObservedTimeout }
     * 
     */
    public SetObservedTimeout createSourceCommandSetObservedTimeout() {
        return new SetObservedTimeout();
    }

    /**
     * Create an instance of {@link SetTimeUTC }
     * 
     */
    public SetTimeUTC createReaderDeviceCommandSetTimeUTC() {
        return new SetTimeUTC();
    }

    /**
     * Create an instance of {@link SetMemoryBank }
     * 
     */
    public SetMemoryBank createTagFieldCommandSetMemoryBank() {
        return new SetMemoryBank();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.TagFieldListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.TagFieldListParamType.List createTagFieldListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.TagFieldListParamType.List();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.SourceCommand.GetReadPoint }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.SourceCommand.GetReadPoint createSourceCommandGetReadPoint() {
        return new org.accada.reader.rprm.core.msg.command.SourceCommand.GetReadPoint();
    }

    /**
     * Create an instance of {@link RemoveTagFields }
     * 
     */
    public RemoveTagFields createReaderDeviceCommandRemoveTagFields() {
        return new RemoveTagFields();
    }

    /**
     * Create an instance of {@link TriggerTypeListReturnType }
     * 
     */
    public TriggerTypeListReturnType createTriggerTypeListReturnType() {
        return new TriggerTypeListReturnType();
    }

    /**
     * Create an instance of {@link SourceListParamType }
     * 
     */
    public SourceListParamType createSourceListParamType() {
        return new SourceListParamType();
    }

    /**
     * Create an instance of {@link RemoveReadTriggers }
     * 
     */
    public RemoveReadTriggers createSourceCommandRemoveReadTriggers() {
        return new RemoveReadTriggers();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.SourceCommand.Create }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.SourceCommand.Create createSourceCommandCreate() {
        return new org.accada.reader.rprm.core.msg.command.SourceCommand.Create();
    }

    /**
     * Create an instance of {@link AddFieldNames }
     * 
     */
    public AddFieldNames createDataSelectorCommandAddFieldNames() {
        return new AddFieldNames();
    }

    /**
     * Create an instance of {@link SourceReport }
     * 
     */
    public SourceReport createReadReportTypeSourceReport() {
        return new SourceReport();
    }

    /**
     * Create an instance of {@link ReturnValue }
     * 
     */
    public ReturnValue createTriggerTypeListReturnTypeReturnValue() {
        return new ReturnValue();
    }

    /**
     * Create an instance of {@link AddressReturnType }
     * 
     */
    public AddressReturnType createAddressReturnType() {
        return new AddressReturnType();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.SourceCommand.GetTagSelector }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.SourceCommand.GetTagSelector createSourceCommandGetTagSelector() {
        return new org.accada.reader.rprm.core.msg.command.SourceCommand.GetTagSelector();
    }

    /**
     * Create an instance of {@link HexStringListType }
     * 
     */
    public HexStringListType createHexStringListType() {
        return new HexStringListType();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.StringListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.StringListParamType.List createStringListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.StringListParamType.List();
    }

    /**
     * Create an instance of {@link AddSources }
     * 
     */
    public AddSources createNotificationChannelCommandAddSources() {
        return new AddSources();
    }

    /**
     * Create an instance of {@link SetLostTimeout }
     * 
     */
    public SetLostTimeout createSourceCommandSetLostTimeout() {
        return new SetLostTimeout();
    }

    /**
     * Create an instance of {@link EpcReturnType }
     * 
     */
    public EpcReturnType createEpcReturnType() {
        return new EpcReturnType();
    }

    /**
     * Create an instance of {@link EventTypeCommand }
     * 
     */
    public EventTypeCommand createEventTypeCommand() {
        return new EventTypeCommand();
    }

    /**
     * Create an instance of {@link SetReadCyclesPerTrigger }
     * 
     */
    public SetReadCyclesPerTrigger createSourceCommandSetReadCyclesPerTrigger() {
        return new SetReadCyclesPerTrigger();
    }

    /**
     * Create an instance of {@link SetTagFieldName }
     * 
     */
    public SetTagFieldName createTagFieldCommandSetTagFieldName() {
        return new SetTagFieldName();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link TimeStampReturnType }
     * 
     */
    public TimeStampReturnType createTimeStampReturnType() {
        return new TimeStampReturnType();
    }

    /**
     * Create an instance of {@link ReaderDeviceCommand }
     * 
     */
    public ReaderDeviceCommand createReaderDeviceCommand() {
        return new ReaderDeviceCommand();
    }

    /**
     * Create an instance of {@link TriggerTypeCommand }
     * 
     */
    public TriggerTypeCommand createTriggerTypeCommand() {
        return new TriggerTypeCommand();
    }

    /**
     * Create an instance of {@link EventTypeListReturnValue }
     * 
     */
    public EventTypeListReturnValue createEventTypeListReturnValue() {
        return new EventTypeListReturnValue();
    }

    /**
     * Create an instance of {@link ReadPointListParamType }
     * 
     */
    public ReadPointListParamType createReadPointListParamType() {
        return new ReadPointListParamType();
    }

    /**
     * Create an instance of {@link Kill }
     * 
     */
    public Kill createSourceCommandKill() {
        return new Kill();
    }

    /**
     * Create an instance of {@link IntReturnType }
     * 
     */
    public IntReturnType createIntReturnType() {
        return new IntReturnType();
    }

    /**
     * Create an instance of {@link RemoveFieldNames }
     * 
     */
    public RemoveFieldNames createDataSelectorCommandRemoveFieldNames() {
        return new RemoveFieldNames();
    }

    /**
     * Create an instance of {@link SetObservedThreshold }
     * 
     */
    public SetObservedThreshold createSourceCommandSetObservedThreshold() {
        return new SetObservedThreshold();
    }

    /**
     * Create an instance of {@link RemoveNotificationChannels }
     * 
     */
    public RemoveNotificationChannels createReaderDeviceCommandRemoveNotificationChannels() {
        return new RemoveNotificationChannels();
    }

    /**
     * Create an instance of {@link RemoveTriggers }
     * 
     */
    public RemoveTriggers createReaderDeviceCommandRemoveTriggers() {
        return new RemoveTriggers();
    }

    /**
     * Create an instance of {@link EventTypeListParamType }
     * 
     */
    public EventTypeListParamType createEventTypeListParamType() {
        return new EventTypeListParamType();
    }

    /**
     * Create an instance of {@link TagSelectorCommand }
     * 
     */
    public TagSelectorCommand createTagSelectorCommand() {
        return new TagSelectorCommand();
    }

    /**
     * Create an instance of {@link SourceReturnType }
     * 
     */
    public SourceReturnType createSourceReturnType() {
        return new SourceReturnType();
    }

    /**
     * Create an instance of {@link FieldNameListParamType }
     * 
     */
    public FieldNameListParamType createFieldNameListParamType() {
        return new FieldNameListParamType();
    }

    /**
     * Create an instance of {@link Read }
     * 
     */
    public Read createSourceCommandRead() {
        return new Read();
    }

    /**
     * Create an instance of {@link SetName }
     * 
     */
    public SetName createReaderDeviceCommandSetName() {
        return new SetName();
    }

    /**
     * Create an instance of {@link SetRole }
     * 
     */
    public SetRole createReaderDeviceCommandSetRole() {
        return new SetRole();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.DataSelectorCommand.Create }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.DataSelectorCommand.Create createDataSelectorCommandCreate() {
        return new org.accada.reader.rprm.core.msg.command.DataSelectorCommand.Create();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.HexStringListType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.HexStringListType.List createHexStringListTypeList() {
        return new org.accada.reader.rprm.core.msg.command.HexStringListType.List();
    }

    /**
     * Create an instance of {@link AddReadTriggers }
     * 
     */
    public AddReadTriggers createSourceCommandAddReadTriggers() {
        return new AddReadTriggers();
    }

    /**
     * Create an instance of {@link RemoveEventFilters }
     * 
     */
    public RemoveEventFilters createDataSelectorCommandRemoveEventFilters() {
        return new RemoveEventFilters();
    }

    /**
     * Create an instance of {@link org.accada.reader.rprm.core.msg.command.EventTypeListParamType.List }
     * 
     */
    public org.accada.reader.rprm.core.msg.command.EventTypeListParamType.List createEventTypeListParamTypeList() {
        return new org.accada.reader.rprm.core.msg.command.EventTypeListParamType.List();
    }

    /**
     * Create an instance of {@link TriggerListReturnType }
     * 
     */
    public TriggerListReturnType createTriggerListReturnType() {
        return new TriggerListReturnType();
    }

    /**
     * Create an instance of {@link SetDataSelector }
     * 
     */
    public SetDataSelector createNotificationChannelCommandSetDataSelector() {
        return new SetDataSelector();
    }

    /**
     * Create an instance of {@link TagSelectorListParamType }
     * 
     */
    public TagSelectorListParamType createTagSelectorListParamType() {
        return new TagSelectorListParamType();
    }

    /**
     * Create an instance of {@link DataSelectorReturnType }
     * 
     */
    public DataSelectorReturnType createDataSelectorReturnType() {
        return new DataSelectorReturnType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value", scope = org.accada.reader.rprm.core.msg.command.HexStringListType.List.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    public JAXBElement<byte[]> createHexStringListTypeListValue(byte[] value) {
        return new JAXBElement<byte[]>(_HexStringListTypeListValue_QNAME, byte[].class, org.accada.reader.rprm.core.msg.command.HexStringListType.List.class, ((byte[]) value));
    }

}
