/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Accada (www.accada.org).
 *
 * Accada is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Accada is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Accada; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.05 at 04:25:04 PM CEST 
//


package org.accada.reader.rprm.core.msg.notification;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.accada.reader.rprm.core.msg.notification.NoParamType;
import org.accada.reader.rprm.core.msg.notification.Notification;
import org.accada.reader.rprm.core.msg.notification.ReadReportType;
import org.accada.reader.rprm.core.msg.notification.ReaderType;
import org.w3c.dom.Element;


/**
 *  This element defines a reader protocol notification.
 * 
 * <p>Java class for notification element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="notification">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="reader" type="{urn:epcglobal:rp:xsd:1}ReaderType" minOccurs="0"/>
 *           &lt;element name="notifyTriggerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="notifyChannelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;choice>
 *             &lt;element name="goodBye" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *             &lt;element name="readReport" type="{urn:epcglobal:rp:xsd:1}ReadReportType" maxOccurs="unbounded"/>
 *             &lt;any/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "reader",
    "notifyTriggerName",
    "notifyChannelName",
    "goodBye",
    "readReport",
    "any"
})
@XmlRootElement(name = "notification")
public class Notification {

    protected String id;
    protected ReaderType reader;
    protected String notifyTriggerName;
    protected String notifyChannelName;
    protected NoParamType goodBye;
    protected List<ReadReportType> readReport;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the reader property.
     * 
     * @return
     *     possible object is
     *     {@link ReaderType }
     *     
     */
    public ReaderType getReader() {
        return reader;
    }

    /**
     * Sets the value of the reader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReaderType }
     *     
     */
    public void setReader(ReaderType value) {
        this.reader = value;
    }

    /**
     * Gets the value of the notifyTriggerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyTriggerName() {
        return notifyTriggerName;
    }

    /**
     * Sets the value of the notifyTriggerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyTriggerName(String value) {
        this.notifyTriggerName = value;
    }

    /**
     * Gets the value of the notifyChannelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyChannelName() {
        return notifyChannelName;
    }

    /**
     * Sets the value of the notifyChannelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyChannelName(String value) {
        this.notifyChannelName = value;
    }

    /**
     * Gets the value of the goodBye property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGoodBye() {
        return goodBye;
    }

    /**
     * Sets the value of the goodBye property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGoodBye(NoParamType value) {
        this.goodBye = value;
    }

    /**
     * Gets the value of the readReport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the readReport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReadReport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReadReportType }
     * 
     * 
     */
    public List<ReadReportType> getReadReport() {
        if (readReport == null) {
            readReport = new ArrayList<ReadReportType>();
        }
        return this.readReport;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
