/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Fosstrak (www.fosstrak.org).
 *
 * Fosstrak is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Fosstrak is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Fosstrak; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

package org.fosstrak.reader.rprm.core.msg;

import javax.xml.bind.JAXBException;

/**
 * Exception which is thrown if the serializing could not be processed successfully.
 * This is a wrapper of different serializer exceptions, i.e., for the JAXBException
 * and others generated by the different serializer implementations.
 * 
 * @author Andreas Fürer, ETH Zurich Switzerland, Winter 2005/06
 *
 */
public class MessageSerializingException extends Exception {

	/**
	 * The serialVersionUID.
	 */
	private static final long serialVersionUID = 6177413187588954646L;

	public MessageSerializingException(String errorMessage) {
		super(errorMessage);
	}

	public MessageSerializingException(JAXBException e) {
		super(e.getMessage(), e.getCause());
	}

}
