/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Accada (www.accada.org).
 *
 * Accada is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Accada is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Accada; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2005.12.06 um 10:39:40 CET 
//


package org.accada.reader.rprm.core.msg.reply;


/**
 * Java content class for AntennaReadPointReply complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Documents%20and%20Settings/fuerera/workspace/JAXP_epc/RpReply.xsd line 138)
 * <p>
 * <pre>
 * &lt;complexType name="AntennaReadPointReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="getReadCount">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getFailedReadCount">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getWriteCount">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getFailedWriteCount">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getKillCount">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="getFailedKillCount">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface AntennaReadPointReply {


    /**
     * reply for get failed write count
     * 
     * @return
     *     possible object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedWriteCountType}
     */
    org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedWriteCountType getGetFailedWriteCount();

    /**
     * reply for get failed write count
     * 
     * @param value
     *     allowed object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedWriteCountType}
     */
    void setGetFailedWriteCount(org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedWriteCountType value);

    /**
     * reply for get read count
     * 
     * @return
     *     possible object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetReadCountType}
     */
    org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetReadCountType getGetReadCount();

    /**
     * reply for get read count
     * 
     * @param value
     *     allowed object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetReadCountType}
     */
    void setGetReadCount(org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetReadCountType value);

    /**
     * reply for get failed read count
     * 
     * @return
     *     possible object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedReadCountType}
     */
    org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedReadCountType getGetFailedReadCount();

    /**
     * reply for get failed read count
     * 
     * @param value
     *     allowed object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedReadCountType}
     */
    void setGetFailedReadCount(org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedReadCountType value);

    /**
     * reply for get kill count
     * 
     * @return
     *     possible object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetKillCountType}
     */
    org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetKillCountType getGetKillCount();

    /**
     * reply for get kill count
     * 
     * @param value
     *     allowed object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetKillCountType}
     */
    void setGetKillCount(org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetKillCountType value);

    /**
     * reply for get write count
     * 
     * @return
     *     possible object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetWriteCountType}
     */
    org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetWriteCountType getGetWriteCount();

    /**
     * reply for get write count
     * 
     * @param value
     *     allowed object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetWriteCountType}
     */
    void setGetWriteCount(org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetWriteCountType value);

    /**
     * reply for get failed kill count
     * 
     * @return
     *     possible object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedKillCountType}
     */
    org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedKillCountType getGetFailedKillCount();

    /**
     * reply for get failed kill count
     * 
     * @param value
     *     allowed object is
     *     {@link org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedKillCountType}
     */
    void setGetFailedKillCount(org.accada.reader.rprm.core.msg.reply.AntennaReadPointReply.GetFailedKillCountType value);


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Documents%20and%20Settings/fuerera/workspace/JAXP_epc/RpReply.xsd line 217)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface GetFailedKillCountType {


        /**
         * count of failed kill tag executions
         * 
         */
        int getReturnValue();

        /**
         * count of failed kill tag executions
         * 
         */
        void setReturnValue(int value);

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Documents%20and%20Settings/fuerera/workspace/JAXP_epc/RpReply.xsd line 161)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface GetFailedReadCountType {


        /**
         * count of failed reads
         * 
         */
        int getReturnValue();

        /**
         * count of failed reads
         * 
         */
        void setReturnValue(int value);

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Documents%20and%20Settings/fuerera/workspace/JAXP_epc/RpReply.xsd line 189)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface GetFailedWriteCountType {


        /**
         * count of failed writes
         * 
         */
        int getReturnValue();

        /**
         * count of failed writes
         * 
         */
        void setReturnValue(int value);

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Documents%20and%20Settings/fuerera/workspace/JAXP_epc/RpReply.xsd line 203)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface GetKillCountType {


        /**
         * count of total kill tag executions
         * 
         */
        int getReturnValue();

        /**
         * count of total kill tag executions
         * 
         */
        void setReturnValue(int value);

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Documents%20and%20Settings/fuerera/workspace/JAXP_epc/RpReply.xsd line 147)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface GetReadCountType {


        /**
         * count of total reads
         * 
         */
        int getReturnValue();

        /**
         * count of total reads
         * 
         */
        void setReturnValue(int value);

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Documents%20and%20Settings/fuerera/workspace/JAXP_epc/RpReply.xsd line 175)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface GetWriteCountType {


        /**
         * count of total writes
         * 
         */
        int getReturnValue();

        /**
         * count of total writes
         * 
         */
        void setReturnValue(int value);

    }

}
