/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Accada (www.accada.org).
 *
 * Accada is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Accada is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Accada; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.05 at 05:26:35 PM CEST 
//


package org.accada.reader.rprm.core.msg.reply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;

import org.accada.reader.rprm.core.msg.reply.DataSelectorListReturnType;
import org.accada.reader.rprm.core.msg.reply.DataSelectorReturnType;
import org.accada.reader.rprm.core.msg.reply.EpcReturnType;
import org.accada.reader.rprm.core.msg.reply.IntReturnType;
import org.accada.reader.rprm.core.msg.reply.NoParamType;
import org.accada.reader.rprm.core.msg.reply.NotificationChannelListReturnType;
import org.accada.reader.rprm.core.msg.reply.NotificationChannelReturnType;
import org.accada.reader.rprm.core.msg.reply.ReadPointListReturnType;
import org.accada.reader.rprm.core.msg.reply.ReadPointReturnType;
import org.accada.reader.rprm.core.msg.reply.ReaderDeviceReply;
import org.accada.reader.rprm.core.msg.reply.SourceListReturnType;
import org.accada.reader.rprm.core.msg.reply.SourceReturnType;
import org.accada.reader.rprm.core.msg.reply.StringReturnType;
import org.accada.reader.rprm.core.msg.reply.TagFieldListReturnType;
import org.accada.reader.rprm.core.msg.reply.TagFieldReturnType;
import org.accada.reader.rprm.core.msg.reply.TagSelectorListReturnType;
import org.accada.reader.rprm.core.msg.reply.TagSelectorReturnType;
import org.accada.reader.rprm.core.msg.reply.TimeStampReturnType;
import org.accada.reader.rprm.core.msg.reply.TriggerListReturnType;
import org.accada.reader.rprm.core.msg.reply.TriggerReturnType;
import org.w3c.dom.Element;


/**
 * <p>Java class for ReaderDeviceReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReaderDeviceReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="getEPC" type="{urn:epcglobal:rp:xsd:1}epcReturnType"/>
 *         &lt;element name="getManufacturer" type="{urn:epcglobal:rp:xsd:1}stringReturnType"/>
 *         &lt;element name="getModel" type="{urn:epcglobal:rp:xsd:1}stringReturnType"/>
 *         &lt;element name="getHandle" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setHandle" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getName" type="{urn:epcglobal:rp:xsd:1}stringReturnType"/>
 *         &lt;element name="setName" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getRole" type="{urn:epcglobal:rp:xsd:1}stringReturnType"/>
 *         &lt;element name="setRole" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getTimeTicks" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="getTimeUTC" type="{urn:epcglobal:rp:xsd:1}timeStampReturnType"/>
 *         &lt;element name="setTimeUTC" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getManufacturerDescription" type="{urn:epcglobal:rp:xsd:1}stringReturnType"/>
 *         &lt;element name="getCurrentSource" type="{urn:epcglobal:rp:xsd:1}SourceReturnType"/>
 *         &lt;element name="setCurrentSource" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getCurrentDataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorReturnType"/>
 *         &lt;element name="setCurrentDataSelector" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeSources" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeAllSources" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getSource" type="{urn:epcglobal:rp:xsd:1}SourceReturnType"/>
 *         &lt;element name="getAllSources" type="{urn:epcglobal:rp:xsd:1}SourceListReturnType"/>
 *         &lt;element name="removeDataSelectors" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeAllDataSelectors" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getDataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorReturnType"/>
 *         &lt;element name="getAllDataSelectors" type="{urn:epcglobal:rp:xsd:1}DataSelectorListReturnType"/>
 *         &lt;element name="removeNotificationChannels" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeAllNotificationChannels" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getNotificationChannel" type="{urn:epcglobal:rp:xsd:1}NotificationChannelReturnType"/>
 *         &lt;element name="getAllNotificationChannels" type="{urn:epcglobal:rp:xsd:1}NotificationChannelListReturnType"/>
 *         &lt;element name="removeTriggers" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeAllTriggers" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getTrigger" type="{urn:epcglobal:rp:xsd:1}TriggerReturnType"/>
 *         &lt;element name="getAllTriggers" type="{urn:epcglobal:rp:xsd:1}TriggerListReturnType"/>
 *         &lt;element name="removeTagSelectors" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeAllTagSelectors" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getTagSelector" type="{urn:epcglobal:rp:xsd:1}TagSelectorReturnType"/>
 *         &lt;element name="getAllTagSelectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListReturnType"/>
 *         &lt;element name="removeTagFields" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeAllTagFields" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getTagField" type="{urn:epcglobal:rp:xsd:1}TagFieldReturnType"/>
 *         &lt;element name="getAllTagFields" type="{urn:epcglobal:rp:xsd:1}TagFieldListReturnType"/>
 *         &lt;element name="resetToDefaultSettings" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="reboot" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="goodbye" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getReadPoint" type="{urn:epcglobal:rp:xsd:1}ReadPointReturnType"/>
 *         &lt;element name="getAllReadPoints" type="{urn:epcglobal:rp:xsd:1}ReadPointListReturnType"/>
 *         &lt;any/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReaderDeviceReply", propOrder = {
    "getEPC",
    "getManufacturer",
    "getModel",
    "getHandle",
    "setHandle",
    "getName",
    "setName",
    "getRole",
    "setRole",
    "getTimeTicks",
    "getTimeUTC",
    "setTimeUTC",
    "getManufacturerDescription",
    "getCurrentSource",
    "setCurrentSource",
    "getCurrentDataSelector",
    "setCurrentDataSelector",
    "removeSources",
    "removeAllSources",
    "getSource",
    "getAllSources",
    "removeDataSelectors",
    "removeAllDataSelectors",
    "getDataSelector",
    "getAllDataSelectors",
    "removeNotificationChannels",
    "removeAllNotificationChannels",
    "getNotificationChannel",
    "getAllNotificationChannels",
    "removeTriggers",
    "removeAllTriggers",
    "getTrigger",
    "getAllTriggers",
    "removeTagSelectors",
    "removeAllTagSelectors",
    "getTagSelector",
    "getAllTagSelectors",
    "removeTagFields",
    "removeAllTagFields",
    "getTagField",
    "getAllTagFields",
    "resetToDefaultSettings",
    "reboot",
    "goodbye",
    "getReadPoint",
    "getAllReadPoints",
    "any"
})
public class ReaderDeviceReply {

    protected EpcReturnType getEPC;
    protected StringReturnType getManufacturer;
    protected StringReturnType getModel;
    protected IntReturnType getHandle;
    protected NoParamType setHandle;
    protected StringReturnType getName;
    protected NoParamType setName;
    protected StringReturnType getRole;
    protected NoParamType setRole;
    protected IntReturnType getTimeTicks;
    protected TimeStampReturnType getTimeUTC;
    protected NoParamType setTimeUTC;
    protected StringReturnType getManufacturerDescription;
    protected SourceReturnType getCurrentSource;
    protected NoParamType setCurrentSource;
    protected DataSelectorReturnType getCurrentDataSelector;
    protected NoParamType setCurrentDataSelector;
    protected NoParamType removeSources;
    protected NoParamType removeAllSources;
    protected SourceReturnType getSource;
    protected SourceListReturnType getAllSources;
    protected NoParamType removeDataSelectors;
    protected NoParamType removeAllDataSelectors;
    protected DataSelectorReturnType getDataSelector;
    protected DataSelectorListReturnType getAllDataSelectors;
    protected NoParamType removeNotificationChannels;
    protected NoParamType removeAllNotificationChannels;
    protected NotificationChannelReturnType getNotificationChannel;
    protected NotificationChannelListReturnType getAllNotificationChannels;
    protected NoParamType removeTriggers;
    protected NoParamType removeAllTriggers;
    protected TriggerReturnType getTrigger;
    protected TriggerListReturnType getAllTriggers;
    protected NoParamType removeTagSelectors;
    protected NoParamType removeAllTagSelectors;
    protected TagSelectorReturnType getTagSelector;
    protected TagSelectorListReturnType getAllTagSelectors;
    protected NoParamType removeTagFields;
    protected NoParamType removeAllTagFields;
    protected TagFieldReturnType getTagField;
    protected TagFieldListReturnType getAllTagFields;
    protected NoParamType resetToDefaultSettings;
    protected NoParamType reboot;
    protected NoParamType goodbye;
    protected ReadPointReturnType getReadPoint;
    protected ReadPointListReturnType getAllReadPoints;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the getEPC property.
     * 
     * @return
     *     possible object is
     *     {@link EpcReturnType }
     *     
     */
    public EpcReturnType getGetEPC() {
        return getEPC;
    }

    /**
     * Sets the value of the getEPC property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpcReturnType }
     *     
     */
    public void setGetEPC(EpcReturnType value) {
        this.getEPC = value;
    }

    /**
     * Gets the value of the getManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link StringReturnType }
     *     
     */
    public StringReturnType getGetManufacturer() {
        return getManufacturer;
    }

    /**
     * Sets the value of the getManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringReturnType }
     *     
     */
    public void setGetManufacturer(StringReturnType value) {
        this.getManufacturer = value;
    }

    /**
     * Gets the value of the getModel property.
     * 
     * @return
     *     possible object is
     *     {@link StringReturnType }
     *     
     */
    public StringReturnType getGetModel() {
        return getModel;
    }

    /**
     * Sets the value of the getModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringReturnType }
     *     
     */
    public void setGetModel(StringReturnType value) {
        this.getModel = value;
    }

    /**
     * Gets the value of the getHandle property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetHandle() {
        return getHandle;
    }

    /**
     * Sets the value of the getHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetHandle(IntReturnType value) {
        this.getHandle = value;
    }

    /**
     * Gets the value of the setHandle property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetHandle() {
        return setHandle;
    }

    /**
     * Sets the value of the setHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetHandle(NoParamType value) {
        this.setHandle = value;
    }

    /**
     * Gets the value of the getName property.
     * 
     * @return
     *     possible object is
     *     {@link StringReturnType }
     *     
     */
    public StringReturnType getGetName() {
        return getName;
    }

    /**
     * Sets the value of the getName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringReturnType }
     *     
     */
    public void setGetName(StringReturnType value) {
        this.getName = value;
    }

    /**
     * Gets the value of the setName property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetName() {
        return setName;
    }

    /**
     * Sets the value of the setName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetName(NoParamType value) {
        this.setName = value;
    }

    /**
     * Gets the value of the getRole property.
     * 
     * @return
     *     possible object is
     *     {@link StringReturnType }
     *     
     */
    public StringReturnType getGetRole() {
        return getRole;
    }

    /**
     * Sets the value of the getRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringReturnType }
     *     
     */
    public void setGetRole(StringReturnType value) {
        this.getRole = value;
    }

    /**
     * Gets the value of the setRole property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetRole() {
        return setRole;
    }

    /**
     * Sets the value of the setRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetRole(NoParamType value) {
        this.setRole = value;
    }

    /**
     * Gets the value of the getTimeTicks property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetTimeTicks() {
        return getTimeTicks;
    }

    /**
     * Sets the value of the getTimeTicks property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetTimeTicks(IntReturnType value) {
        this.getTimeTicks = value;
    }

    /**
     * Gets the value of the getTimeUTC property.
     * 
     * @return
     *     possible object is
     *     {@link TimeStampReturnType }
     *     
     */
    public TimeStampReturnType getGetTimeUTC() {
        return getTimeUTC;
    }

    /**
     * Sets the value of the getTimeUTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeStampReturnType }
     *     
     */
    public void setGetTimeUTC(TimeStampReturnType value) {
        this.getTimeUTC = value;
    }

    /**
     * Gets the value of the setTimeUTC property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetTimeUTC() {
        return setTimeUTC;
    }

    /**
     * Sets the value of the setTimeUTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetTimeUTC(NoParamType value) {
        this.setTimeUTC = value;
    }

    /**
     * Gets the value of the getManufacturerDescription property.
     * 
     * @return
     *     possible object is
     *     {@link StringReturnType }
     *     
     */
    public StringReturnType getGetManufacturerDescription() {
        return getManufacturerDescription;
    }

    /**
     * Sets the value of the getManufacturerDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringReturnType }
     *     
     */
    public void setGetManufacturerDescription(StringReturnType value) {
        this.getManufacturerDescription = value;
    }

    /**
     * Gets the value of the getCurrentSource property.
     * 
     * @return
     *     possible object is
     *     {@link SourceReturnType }
     *     
     */
    public SourceReturnType getGetCurrentSource() {
        return getCurrentSource;
    }

    /**
     * Sets the value of the getCurrentSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceReturnType }
     *     
     */
    public void setGetCurrentSource(SourceReturnType value) {
        this.getCurrentSource = value;
    }

    /**
     * Gets the value of the setCurrentSource property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetCurrentSource() {
        return setCurrentSource;
    }

    /**
     * Sets the value of the setCurrentSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetCurrentSource(NoParamType value) {
        this.setCurrentSource = value;
    }

    /**
     * Gets the value of the getCurrentDataSelector property.
     * 
     * @return
     *     possible object is
     *     {@link DataSelectorReturnType }
     *     
     */
    public DataSelectorReturnType getGetCurrentDataSelector() {
        return getCurrentDataSelector;
    }

    /**
     * Sets the value of the getCurrentDataSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSelectorReturnType }
     *     
     */
    public void setGetCurrentDataSelector(DataSelectorReturnType value) {
        this.getCurrentDataSelector = value;
    }

    /**
     * Gets the value of the setCurrentDataSelector property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetCurrentDataSelector() {
        return setCurrentDataSelector;
    }

    /**
     * Sets the value of the setCurrentDataSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetCurrentDataSelector(NoParamType value) {
        this.setCurrentDataSelector = value;
    }

    /**
     * Gets the value of the removeSources property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveSources() {
        return removeSources;
    }

    /**
     * Sets the value of the removeSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveSources(NoParamType value) {
        this.removeSources = value;
    }

    /**
     * Gets the value of the removeAllSources property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllSources() {
        return removeAllSources;
    }

    /**
     * Sets the value of the removeAllSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllSources(NoParamType value) {
        this.removeAllSources = value;
    }

    /**
     * Gets the value of the getSource property.
     * 
     * @return
     *     possible object is
     *     {@link SourceReturnType }
     *     
     */
    public SourceReturnType getGetSource() {
        return getSource;
    }

    /**
     * Sets the value of the getSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceReturnType }
     *     
     */
    public void setGetSource(SourceReturnType value) {
        this.getSource = value;
    }

    /**
     * Gets the value of the getAllSources property.
     * 
     * @return
     *     possible object is
     *     {@link SourceListReturnType }
     *     
     */
    public SourceListReturnType getGetAllSources() {
        return getAllSources;
    }

    /**
     * Sets the value of the getAllSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceListReturnType }
     *     
     */
    public void setGetAllSources(SourceListReturnType value) {
        this.getAllSources = value;
    }

    /**
     * Gets the value of the removeDataSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveDataSelectors() {
        return removeDataSelectors;
    }

    /**
     * Sets the value of the removeDataSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveDataSelectors(NoParamType value) {
        this.removeDataSelectors = value;
    }

    /**
     * Gets the value of the removeAllDataSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllDataSelectors() {
        return removeAllDataSelectors;
    }

    /**
     * Sets the value of the removeAllDataSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllDataSelectors(NoParamType value) {
        this.removeAllDataSelectors = value;
    }

    /**
     * Gets the value of the getDataSelector property.
     * 
     * @return
     *     possible object is
     *     {@link DataSelectorReturnType }
     *     
     */
    public DataSelectorReturnType getGetDataSelector() {
        return getDataSelector;
    }

    /**
     * Sets the value of the getDataSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSelectorReturnType }
     *     
     */
    public void setGetDataSelector(DataSelectorReturnType value) {
        this.getDataSelector = value;
    }

    /**
     * Gets the value of the getAllDataSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link DataSelectorListReturnType }
     *     
     */
    public DataSelectorListReturnType getGetAllDataSelectors() {
        return getAllDataSelectors;
    }

    /**
     * Sets the value of the getAllDataSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSelectorListReturnType }
     *     
     */
    public void setGetAllDataSelectors(DataSelectorListReturnType value) {
        this.getAllDataSelectors = value;
    }

    /**
     * Gets the value of the removeNotificationChannels property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveNotificationChannels() {
        return removeNotificationChannels;
    }

    /**
     * Sets the value of the removeNotificationChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveNotificationChannels(NoParamType value) {
        this.removeNotificationChannels = value;
    }

    /**
     * Gets the value of the removeAllNotificationChannels property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllNotificationChannels() {
        return removeAllNotificationChannels;
    }

    /**
     * Sets the value of the removeAllNotificationChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllNotificationChannels(NoParamType value) {
        this.removeAllNotificationChannels = value;
    }

    /**
     * Gets the value of the getNotificationChannel property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationChannelReturnType }
     *     
     */
    public NotificationChannelReturnType getGetNotificationChannel() {
        return getNotificationChannel;
    }

    /**
     * Sets the value of the getNotificationChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationChannelReturnType }
     *     
     */
    public void setGetNotificationChannel(NotificationChannelReturnType value) {
        this.getNotificationChannel = value;
    }

    /**
     * Gets the value of the getAllNotificationChannels property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationChannelListReturnType }
     *     
     */
    public NotificationChannelListReturnType getGetAllNotificationChannels() {
        return getAllNotificationChannels;
    }

    /**
     * Sets the value of the getAllNotificationChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationChannelListReturnType }
     *     
     */
    public void setGetAllNotificationChannels(NotificationChannelListReturnType value) {
        this.getAllNotificationChannels = value;
    }

    /**
     * Gets the value of the removeTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveTriggers() {
        return removeTriggers;
    }

    /**
     * Sets the value of the removeTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveTriggers(NoParamType value) {
        this.removeTriggers = value;
    }

    /**
     * Gets the value of the removeAllTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllTriggers() {
        return removeAllTriggers;
    }

    /**
     * Sets the value of the removeAllTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllTriggers(NoParamType value) {
        this.removeAllTriggers = value;
    }

    /**
     * Gets the value of the getTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerReturnType }
     *     
     */
    public TriggerReturnType getGetTrigger() {
        return getTrigger;
    }

    /**
     * Sets the value of the getTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerReturnType }
     *     
     */
    public void setGetTrigger(TriggerReturnType value) {
        this.getTrigger = value;
    }

    /**
     * Gets the value of the getAllTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerListReturnType }
     *     
     */
    public TriggerListReturnType getGetAllTriggers() {
        return getAllTriggers;
    }

    /**
     * Sets the value of the getAllTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerListReturnType }
     *     
     */
    public void setGetAllTriggers(TriggerListReturnType value) {
        this.getAllTriggers = value;
    }

    /**
     * Gets the value of the removeTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveTagSelectors() {
        return removeTagSelectors;
    }

    /**
     * Sets the value of the removeTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveTagSelectors(NoParamType value) {
        this.removeTagSelectors = value;
    }

    /**
     * Gets the value of the removeAllTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllTagSelectors() {
        return removeAllTagSelectors;
    }

    /**
     * Sets the value of the removeAllTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllTagSelectors(NoParamType value) {
        this.removeAllTagSelectors = value;
    }

    /**
     * Gets the value of the getTagSelector property.
     * 
     * @return
     *     possible object is
     *     {@link TagSelectorReturnType }
     *     
     */
    public TagSelectorReturnType getGetTagSelector() {
        return getTagSelector;
    }

    /**
     * Sets the value of the getTagSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagSelectorReturnType }
     *     
     */
    public void setGetTagSelector(TagSelectorReturnType value) {
        this.getTagSelector = value;
    }

    /**
     * Gets the value of the getAllTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link TagSelectorListReturnType }
     *     
     */
    public TagSelectorListReturnType getGetAllTagSelectors() {
        return getAllTagSelectors;
    }

    /**
     * Sets the value of the getAllTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagSelectorListReturnType }
     *     
     */
    public void setGetAllTagSelectors(TagSelectorListReturnType value) {
        this.getAllTagSelectors = value;
    }

    /**
     * Gets the value of the removeTagFields property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveTagFields() {
        return removeTagFields;
    }

    /**
     * Sets the value of the removeTagFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveTagFields(NoParamType value) {
        this.removeTagFields = value;
    }

    /**
     * Gets the value of the removeAllTagFields property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllTagFields() {
        return removeAllTagFields;
    }

    /**
     * Sets the value of the removeAllTagFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllTagFields(NoParamType value) {
        this.removeAllTagFields = value;
    }

    /**
     * Gets the value of the getTagField property.
     * 
     * @return
     *     possible object is
     *     {@link TagFieldReturnType }
     *     
     */
    public TagFieldReturnType getGetTagField() {
        return getTagField;
    }

    /**
     * Sets the value of the getTagField property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagFieldReturnType }
     *     
     */
    public void setGetTagField(TagFieldReturnType value) {
        this.getTagField = value;
    }

    /**
     * Gets the value of the getAllTagFields property.
     * 
     * @return
     *     possible object is
     *     {@link TagFieldListReturnType }
     *     
     */
    public TagFieldListReturnType getGetAllTagFields() {
        return getAllTagFields;
    }

    /**
     * Sets the value of the getAllTagFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagFieldListReturnType }
     *     
     */
    public void setGetAllTagFields(TagFieldListReturnType value) {
        this.getAllTagFields = value;
    }

    /**
     * Gets the value of the resetToDefaultSettings property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getResetToDefaultSettings() {
        return resetToDefaultSettings;
    }

    /**
     * Sets the value of the resetToDefaultSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setResetToDefaultSettings(NoParamType value) {
        this.resetToDefaultSettings = value;
    }

    /**
     * Gets the value of the reboot property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getReboot() {
        return reboot;
    }

    /**
     * Sets the value of the reboot property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setReboot(NoParamType value) {
        this.reboot = value;
    }

    /**
     * Gets the value of the goodbye property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getGoodbye() {
        return goodbye;
    }

    /**
     * Sets the value of the goodbye property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setGoodbye(NoParamType value) {
        this.goodbye = value;
    }

    /**
     * Gets the value of the getReadPoint property.
     * 
     * @return
     *     possible object is
     *     {@link ReadPointReturnType }
     *     
     */
    public ReadPointReturnType getGetReadPoint() {
        return getReadPoint;
    }

    /**
     * Sets the value of the getReadPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadPointReturnType }
     *     
     */
    public void setGetReadPoint(ReadPointReturnType value) {
        this.getReadPoint = value;
    }

    /**
     * Gets the value of the getAllReadPoints property.
     * 
     * @return
     *     possible object is
     *     {@link ReadPointListReturnType }
     *     
     */
    public ReadPointListReturnType getGetAllReadPoints() {
        return getAllReadPoints;
    }

    /**
     * Sets the value of the getAllReadPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadPointListReturnType }
     *     
     */
    public void setGetAllReadPoints(ReadPointListReturnType value) {
        this.getAllReadPoints = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
