/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Fosstrak (www.fosstrak.org).
 *
 * Fosstrak is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Fosstrak is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Fosstrak; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.05 at 05:26:35 PM CEST 
//


package org.fosstrak.reader.rprm.core.msg.reply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.fosstrak.reader.rprm.core.msg.reply.DataSelectorReply;
import org.fosstrak.reader.rprm.core.msg.reply.ErrorType;
import org.fosstrak.reader.rprm.core.msg.reply.EventTypeReply;
import org.fosstrak.reader.rprm.core.msg.reply.FieldNameReply;
import org.fosstrak.reader.rprm.core.msg.reply.NotificationChannelReply;
import org.fosstrak.reader.rprm.core.msg.reply.ReadPointReply;
import org.fosstrak.reader.rprm.core.msg.reply.ReaderDeviceReply;
import org.fosstrak.reader.rprm.core.msg.reply.Reply;
import org.fosstrak.reader.rprm.core.msg.reply.SourceReply;
import org.fosstrak.reader.rprm.core.msg.reply.TagFieldReply;
import org.fosstrak.reader.rprm.core.msg.reply.TagSelectorReply;
import org.fosstrak.reader.rprm.core.msg.reply.TriggerReply;
import org.fosstrak.reader.rprm.core.msg.reply.TriggerTypeReply;
import org.w3c.dom.Element;


/**
 *  This element defines a reader protocol reply. Just
 *                 like commands, replies are grouped by the object they belong to. To specify the
 *                 object a reply relates to, the name of the object is used. All the replies contain a
 *                 single return value inside the reply. return value is enclosed by the element
 *                 "returnValue". In case of a single return value it is directly added to this
 *                 element. In case of an array of return values they are enclosed within element
 *                 "list" with each value in turn enclosed in element "value". Each reply is wrapped in
 * 
 *                 its object type. 
 * 
 * <p>Java class for reply element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="reply">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="resultCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *           &lt;choice>
 *             &lt;element name="error" type="{urn:epcglobal:rp:xsd:1}ErrorType"/>
 *             &lt;element name="readerDevice" type="{urn:epcglobal:rp:xsd:1}ReaderDeviceReply"/>
 *             &lt;element name="source" type="{urn:epcglobal:rp:xsd:1}SourceReply"/>
 *             &lt;element name="readPoint" type="{urn:epcglobal:rp:xsd:1}ReadPointReply"/>
 *             &lt;element name="trigger" type="{urn:epcglobal:rp:xsd:1}TriggerReply"/>
 *             &lt;element name="tagSelector" type="{urn:epcglobal:rp:xsd:1}TagSelectorReply"/>
 *             &lt;element name="notificationChannel" type="{urn:epcglobal:rp:xsd:1}NotificationChannelReply"/>
 *             &lt;element name="dataSelector" type="{urn:epcglobal:rp:xsd:1}DataSelectorReply"/>
 *             &lt;element name="eventType" type="{urn:epcglobal:rp:xsd:1}EventTypeReply"/>
 *             &lt;element name="triggerType" type="{urn:epcglobal:rp:xsd:1}TriggerTypeReply"/>
 *             &lt;element name="fieldName" type="{urn:epcglobal:rp:xsd:1}FieldNameReply"/>
 *             &lt;element name="tagField" type="{urn:epcglobal:rp:xsd:1}TagFieldReply"/>
 *             &lt;any/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "resultCode",
    "error",
    "readerDevice",
    "source",
    "readPoint",
    "trigger",
    "tagSelector",
    "notificationChannel",
    "dataSelector",
    "eventType",
    "triggerType",
    "fieldName",
    "tagField",
    "any"
})
@XmlRootElement(name = "reply")
public class Reply {

    protected String id;
    @XmlElement(type = Integer.class)
    protected int resultCode;
    protected ErrorType error;
    protected ReaderDeviceReply readerDevice;
    protected SourceReply source;
    protected ReadPointReply readPoint;
    protected TriggerReply trigger;
    protected TagSelectorReply tagSelector;
    protected NotificationChannelReply notificationChannel;
    protected DataSelectorReply dataSelector;
    protected EventTypeReply eventType;
    protected TriggerTypeReply triggerType;
    protected FieldNameReply fieldName;
    protected TagFieldReply tagField;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     */
    public int getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     */
    public void setResultCode(int value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

    /**
     * Gets the value of the readerDevice property.
     * 
     * @return
     *     possible object is
     *     {@link ReaderDeviceReply }
     *     
     */
    public ReaderDeviceReply getReaderDevice() {
        return readerDevice;
    }

    /**
     * Sets the value of the readerDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReaderDeviceReply }
     *     
     */
    public void setReaderDevice(ReaderDeviceReply value) {
        this.readerDevice = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceReply }
     *     
     */
    public SourceReply getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceReply }
     *     
     */
    public void setSource(SourceReply value) {
        this.source = value;
    }

    /**
     * Gets the value of the readPoint property.
     * 
     * @return
     *     possible object is
     *     {@link ReadPointReply }
     *     
     */
    public ReadPointReply getReadPoint() {
        return readPoint;
    }

    /**
     * Sets the value of the readPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadPointReply }
     *     
     */
    public void setReadPoint(ReadPointReply value) {
        this.readPoint = value;
    }

    /**
     * Gets the value of the trigger property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerReply }
     *     
     */
    public TriggerReply getTrigger() {
        return trigger;
    }

    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerReply }
     *     
     */
    public void setTrigger(TriggerReply value) {
        this.trigger = value;
    }

    /**
     * Gets the value of the tagSelector property.
     * 
     * @return
     *     possible object is
     *     {@link TagSelectorReply }
     *     
     */
    public TagSelectorReply getTagSelector() {
        return tagSelector;
    }

    /**
     * Sets the value of the tagSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagSelectorReply }
     *     
     */
    public void setTagSelector(TagSelectorReply value) {
        this.tagSelector = value;
    }

    /**
     * Gets the value of the notificationChannel property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationChannelReply }
     *     
     */
    public NotificationChannelReply getNotificationChannel() {
        return notificationChannel;
    }

    /**
     * Sets the value of the notificationChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationChannelReply }
     *     
     */
    public void setNotificationChannel(NotificationChannelReply value) {
        this.notificationChannel = value;
    }

    /**
     * Gets the value of the dataSelector property.
     * 
     * @return
     *     possible object is
     *     {@link DataSelectorReply }
     *     
     */
    public DataSelectorReply getDataSelector() {
        return dataSelector;
    }

    /**
     * Sets the value of the dataSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSelectorReply }
     *     
     */
    public void setDataSelector(DataSelectorReply value) {
        this.dataSelector = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link EventTypeReply }
     *     
     */
    public EventTypeReply getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTypeReply }
     *     
     */
    public void setEventType(EventTypeReply value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the triggerType property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerTypeReply }
     *     
     */
    public TriggerTypeReply getTriggerType() {
        return triggerType;
    }

    /**
     * Sets the value of the triggerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerTypeReply }
     *     
     */
    public void setTriggerType(TriggerTypeReply value) {
        this.triggerType = value;
    }

    /**
     * Gets the value of the fieldName property.
     * 
     * @return
     *     possible object is
     *     {@link FieldNameReply }
     *     
     */
    public FieldNameReply getFieldName() {
        return fieldName;
    }

    /**
     * Sets the value of the fieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldNameReply }
     *     
     */
    public void setFieldName(FieldNameReply value) {
        this.fieldName = value;
    }

    /**
     * Gets the value of the tagField property.
     * 
     * @return
     *     possible object is
     *     {@link TagFieldReply }
     *     
     */
    public TagFieldReply getTagField() {
        return tagField;
    }

    /**
     * Sets the value of the tagField property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagFieldReply }
     *     
     */
    public void setTagField(TagFieldReply value) {
        this.tagField = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
