/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Accada (www.accada.org).
 *
 * Accada is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Accada is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Accada; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.05 at 05:26:35 PM CEST 
//


package org.accada.reader.rprm.core.msg.reply;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;

import org.accada.reader.rprm.core.msg.reply.BooleanReturnType;
import org.accada.reader.rprm.core.msg.reply.IntReturnType;
import org.accada.reader.rprm.core.msg.reply.NoParamType;
import org.accada.reader.rprm.core.msg.reply.ReadPointListReturnType;
import org.accada.reader.rprm.core.msg.reply.ReadPointReturnType;
import org.accada.reader.rprm.core.msg.reply.ReadReportType;
import org.accada.reader.rprm.core.msg.reply.SourceReply;
import org.accada.reader.rprm.core.msg.reply.SourceReturnType;
import org.accada.reader.rprm.core.msg.reply.StringReturnType;
import org.accada.reader.rprm.core.msg.reply.TagSelectorListReturnType;
import org.accada.reader.rprm.core.msg.reply.TagSelectorReturnType;
import org.accada.reader.rprm.core.msg.reply.TriggerListReturnType;
import org.accada.reader.rprm.core.msg.reply.TriggerReturnType;
import org.accada.reader.rprm.core.msg.reply.SourceReply.RawReadIDs;
import org.accada.reader.rprm.core.msg.reply.SourceReply.Read;
import org.accada.reader.rprm.core.msg.reply.SourceReply.ReadIDs;
import org.w3c.dom.Element;


/**
 * <p>Java class for SourceReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourceReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="create" type="{urn:epcglobal:rp:xsd:1}SourceReturnType"/>
 *         &lt;element name="getName" type="{urn:epcglobal:rp:xsd:1}stringReturnType"/>
 *         &lt;element name="isFixed" type="{urn:epcglobal:rp:xsd:1}booleanReturnType"/>
 *         &lt;element name="addReadPoints" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeReadPoints" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeAllReadPoints" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getReadPoint" type="{urn:epcglobal:rp:xsd:1}ReadPointReturnType"/>
 *         &lt;element name="getAllReadPoints" type="{urn:epcglobal:rp:xsd:1}ReadPointListReturnType"/>
 *         &lt;element name="addReadTriggers" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeReadTriggers" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeAllReadTriggers" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getReadTrigger" type="{urn:epcglobal:rp:xsd:1}TriggerReturnType"/>
 *         &lt;element name="getAllReadTriggers" type="{urn:epcglobal:rp:xsd:1}TriggerListReturnType"/>
 *         &lt;element name="addTagSelectors" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeTagSelectors" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="removeAllTagSelectors" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getTagSelector" type="{urn:epcglobal:rp:xsd:1}TagSelectorReturnType"/>
 *         &lt;element name="getAllTagSelectors" type="{urn:epcglobal:rp:xsd:1}TagSelectorListReturnType"/>
 *         &lt;element name="getGlimpsedTimeout" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setGlimpsedTimeout" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getObservedThreshold" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setObservedThreshold" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getObservedTimeout" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setObservedTimeout" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getLostTimeout" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setLostTimeout" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="rawReadIDs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnValue" type="{urn:epcglobal:rp:xsd:1}ReadReportType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="readIDs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnValue" type="{urn:epcglobal:rp:xsd:1}ReadReportType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="read">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="returnValue" type="{urn:epcglobal:rp:xsd:1}ReadReportType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="writeID" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="write" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="kill" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getReadCyclesPerTrigger" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setReadCyclesPerTrigger" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getMaxReadDutyCycle" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setMaxReadDutyCycle" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getReadTimeout" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setReadTimeout" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getSession" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setSession" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;any/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "SourceReply", propOrder = {
    "create",
    "getName",
    "isFixed",
    "addReadPoints",
    "removeReadPoints",
    "removeAllReadPoints",
    "getReadPoint",
    "getAllReadPoints",
    "addReadTriggers",
    "removeReadTriggers",
    "removeAllReadTriggers",
    "getReadTrigger",
    "getAllReadTriggers",
    "addTagSelectors",
    "removeTagSelectors",
    "removeAllTagSelectors",
    "getTagSelector",
    "getAllTagSelectors",
    "getGlimpsedTimeout",
    "setGlimpsedTimeout",
    "getObservedThreshold",
    "setObservedThreshold",
    "getObservedTimeout",
    "setObservedTimeout",
    "getLostTimeout",
    "setLostTimeout",
    "rawReadIDs",
    "readIDs",
    "read",
    "writeID",
    "write",
    "kill",
    "getReadCyclesPerTrigger",
    "setReadCyclesPerTrigger",
    "getMaxReadDutyCycle",
    "setMaxReadDutyCycle",
    "getReadTimeout",
    "setReadTimeout",
    "getSession",
    "setSession",
    "any"
})
public class SourceReply {

    protected SourceReturnType create;
    protected StringReturnType getName;
    protected BooleanReturnType isFixed;
    protected NoParamType addReadPoints;
    protected NoParamType removeReadPoints;
    protected NoParamType removeAllReadPoints;
    protected ReadPointReturnType getReadPoint;
    protected ReadPointListReturnType getAllReadPoints;
    protected NoParamType addReadTriggers;
    protected NoParamType removeReadTriggers;
    protected NoParamType removeAllReadTriggers;
    protected TriggerReturnType getReadTrigger;
    protected TriggerListReturnType getAllReadTriggers;
    protected NoParamType addTagSelectors;
    protected NoParamType removeTagSelectors;
    protected NoParamType removeAllTagSelectors;
    protected TagSelectorReturnType getTagSelector;
    protected TagSelectorListReturnType getAllTagSelectors;
    protected IntReturnType getGlimpsedTimeout;
    protected NoParamType setGlimpsedTimeout;
    protected IntReturnType getObservedThreshold;
    protected NoParamType setObservedThreshold;
    protected IntReturnType getObservedTimeout;
    protected NoParamType setObservedTimeout;
    protected IntReturnType getLostTimeout;
    protected NoParamType setLostTimeout;
    protected RawReadIDs rawReadIDs;
    protected ReadIDs readIDs;
    protected Read read;
    protected NoParamType writeID;
    protected NoParamType write;
    protected NoParamType kill;
    protected IntReturnType getReadCyclesPerTrigger;
    protected NoParamType setReadCyclesPerTrigger;
    protected IntReturnType getMaxReadDutyCycle;
    protected NoParamType setMaxReadDutyCycle;
    protected IntReturnType getReadTimeout;
    protected NoParamType setReadTimeout;
    protected IntReturnType getSession;
    protected NoParamType setSession;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the create property.
     * 
     * @return
     *     possible object is
     *     {@link SourceReturnType }
     *     
     */
    public SourceReturnType getCreate() {
        return create;
    }

    /**
     * Sets the value of the create property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceReturnType }
     *     
     */
    public void setCreate(SourceReturnType value) {
        this.create = value;
    }

    /**
     * Gets the value of the getName property.
     * 
     * @return
     *     possible object is
     *     {@link StringReturnType }
     *     
     */
    public StringReturnType getGetName() {
        return getName;
    }

    /**
     * Sets the value of the getName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringReturnType }
     *     
     */
    public void setGetName(StringReturnType value) {
        this.getName = value;
    }

    /**
     * Gets the value of the isFixed property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanReturnType }
     *     
     */
    public BooleanReturnType getIsFixed() {
        return isFixed;
    }

    /**
     * Sets the value of the isFixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanReturnType }
     *     
     */
    public void setIsFixed(BooleanReturnType value) {
        this.isFixed = value;
    }

    /**
     * Gets the value of the addReadPoints property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getAddReadPoints() {
        return addReadPoints;
    }

    /**
     * Sets the value of the addReadPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setAddReadPoints(NoParamType value) {
        this.addReadPoints = value;
    }

    /**
     * Gets the value of the removeReadPoints property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveReadPoints() {
        return removeReadPoints;
    }

    /**
     * Sets the value of the removeReadPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveReadPoints(NoParamType value) {
        this.removeReadPoints = value;
    }

    /**
     * Gets the value of the removeAllReadPoints property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllReadPoints() {
        return removeAllReadPoints;
    }

    /**
     * Sets the value of the removeAllReadPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllReadPoints(NoParamType value) {
        this.removeAllReadPoints = value;
    }

    /**
     * Gets the value of the getReadPoint property.
     * 
     * @return
     *     possible object is
     *     {@link ReadPointReturnType }
     *     
     */
    public ReadPointReturnType getGetReadPoint() {
        return getReadPoint;
    }

    /**
     * Sets the value of the getReadPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadPointReturnType }
     *     
     */
    public void setGetReadPoint(ReadPointReturnType value) {
        this.getReadPoint = value;
    }

    /**
     * Gets the value of the getAllReadPoints property.
     * 
     * @return
     *     possible object is
     *     {@link ReadPointListReturnType }
     *     
     */
    public ReadPointListReturnType getGetAllReadPoints() {
        return getAllReadPoints;
    }

    /**
     * Sets the value of the getAllReadPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadPointListReturnType }
     *     
     */
    public void setGetAllReadPoints(ReadPointListReturnType value) {
        this.getAllReadPoints = value;
    }

    /**
     * Gets the value of the addReadTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getAddReadTriggers() {
        return addReadTriggers;
    }

    /**
     * Sets the value of the addReadTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setAddReadTriggers(NoParamType value) {
        this.addReadTriggers = value;
    }

    /**
     * Gets the value of the removeReadTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveReadTriggers() {
        return removeReadTriggers;
    }

    /**
     * Sets the value of the removeReadTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveReadTriggers(NoParamType value) {
        this.removeReadTriggers = value;
    }

    /**
     * Gets the value of the removeAllReadTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllReadTriggers() {
        return removeAllReadTriggers;
    }

    /**
     * Sets the value of the removeAllReadTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllReadTriggers(NoParamType value) {
        this.removeAllReadTriggers = value;
    }

    /**
     * Gets the value of the getReadTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerReturnType }
     *     
     */
    public TriggerReturnType getGetReadTrigger() {
        return getReadTrigger;
    }

    /**
     * Sets the value of the getReadTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerReturnType }
     *     
     */
    public void setGetReadTrigger(TriggerReturnType value) {
        this.getReadTrigger = value;
    }

    /**
     * Gets the value of the getAllReadTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerListReturnType }
     *     
     */
    public TriggerListReturnType getGetAllReadTriggers() {
        return getAllReadTriggers;
    }

    /**
     * Sets the value of the getAllReadTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerListReturnType }
     *     
     */
    public void setGetAllReadTriggers(TriggerListReturnType value) {
        this.getAllReadTriggers = value;
    }

    /**
     * Gets the value of the addTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getAddTagSelectors() {
        return addTagSelectors;
    }

    /**
     * Sets the value of the addTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setAddTagSelectors(NoParamType value) {
        this.addTagSelectors = value;
    }

    /**
     * Gets the value of the removeTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveTagSelectors() {
        return removeTagSelectors;
    }

    /**
     * Sets the value of the removeTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveTagSelectors(NoParamType value) {
        this.removeTagSelectors = value;
    }

    /**
     * Gets the value of the removeAllTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getRemoveAllTagSelectors() {
        return removeAllTagSelectors;
    }

    /**
     * Sets the value of the removeAllTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setRemoveAllTagSelectors(NoParamType value) {
        this.removeAllTagSelectors = value;
    }

    /**
     * Gets the value of the getTagSelector property.
     * 
     * @return
     *     possible object is
     *     {@link TagSelectorReturnType }
     *     
     */
    public TagSelectorReturnType getGetTagSelector() {
        return getTagSelector;
    }

    /**
     * Sets the value of the getTagSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagSelectorReturnType }
     *     
     */
    public void setGetTagSelector(TagSelectorReturnType value) {
        this.getTagSelector = value;
    }

    /**
     * Gets the value of the getAllTagSelectors property.
     * 
     * @return
     *     possible object is
     *     {@link TagSelectorListReturnType }
     *     
     */
    public TagSelectorListReturnType getGetAllTagSelectors() {
        return getAllTagSelectors;
    }

    /**
     * Sets the value of the getAllTagSelectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagSelectorListReturnType }
     *     
     */
    public void setGetAllTagSelectors(TagSelectorListReturnType value) {
        this.getAllTagSelectors = value;
    }

    /**
     * Gets the value of the getGlimpsedTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetGlimpsedTimeout() {
        return getGlimpsedTimeout;
    }

    /**
     * Sets the value of the getGlimpsedTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetGlimpsedTimeout(IntReturnType value) {
        this.getGlimpsedTimeout = value;
    }

    /**
     * Gets the value of the setGlimpsedTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetGlimpsedTimeout() {
        return setGlimpsedTimeout;
    }

    /**
     * Sets the value of the setGlimpsedTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetGlimpsedTimeout(NoParamType value) {
        this.setGlimpsedTimeout = value;
    }

    /**
     * Gets the value of the getObservedThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetObservedThreshold() {
        return getObservedThreshold;
    }

    /**
     * Sets the value of the getObservedThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetObservedThreshold(IntReturnType value) {
        this.getObservedThreshold = value;
    }

    /**
     * Gets the value of the setObservedThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetObservedThreshold() {
        return setObservedThreshold;
    }

    /**
     * Sets the value of the setObservedThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetObservedThreshold(NoParamType value) {
        this.setObservedThreshold = value;
    }

    /**
     * Gets the value of the getObservedTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetObservedTimeout() {
        return getObservedTimeout;
    }

    /**
     * Sets the value of the getObservedTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetObservedTimeout(IntReturnType value) {
        this.getObservedTimeout = value;
    }

    /**
     * Gets the value of the setObservedTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetObservedTimeout() {
        return setObservedTimeout;
    }

    /**
     * Sets the value of the setObservedTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetObservedTimeout(NoParamType value) {
        this.setObservedTimeout = value;
    }

    /**
     * Gets the value of the getLostTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetLostTimeout() {
        return getLostTimeout;
    }

    /**
     * Sets the value of the getLostTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetLostTimeout(IntReturnType value) {
        this.getLostTimeout = value;
    }

    /**
     * Gets the value of the setLostTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetLostTimeout() {
        return setLostTimeout;
    }

    /**
     * Sets the value of the setLostTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetLostTimeout(NoParamType value) {
        this.setLostTimeout = value;
    }

    /**
     * Gets the value of the rawReadIDs property.
     * 
     * @return
     *     possible object is
     *     {@link RawReadIDs }
     *     
     */
    public RawReadIDs getRawReadIDs() {
        return rawReadIDs;
    }

    /**
     * Sets the value of the rawReadIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RawReadIDs }
     *     
     */
    public void setRawReadIDs(RawReadIDs value) {
        this.rawReadIDs = value;
    }

    /**
     * Gets the value of the readIDs property.
     * 
     * @return
     *     possible object is
     *     {@link ReadIDs }
     *     
     */
    public ReadIDs getReadIDs() {
        return readIDs;
    }

    /**
     * Sets the value of the readIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadIDs }
     *     
     */
    public void setReadIDs(ReadIDs value) {
        this.readIDs = value;
    }

    /**
     * Gets the value of the read property.
     * 
     * @return
     *     possible object is
     *     {@link Read }
     *     
     */
    public Read getRead() {
        return read;
    }

    /**
     * Sets the value of the read property.
     * 
     * @param value
     *     allowed object is
     *     {@link Read }
     *     
     */
    public void setRead(Read value) {
        this.read = value;
    }

    /**
     * Gets the value of the writeID property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getWriteID() {
        return writeID;
    }

    /**
     * Sets the value of the writeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setWriteID(NoParamType value) {
        this.writeID = value;
    }

    /**
     * Gets the value of the write property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getWrite() {
        return write;
    }

    /**
     * Sets the value of the write property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setWrite(NoParamType value) {
        this.write = value;
    }

    /**
     * Gets the value of the kill property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getKill() {
        return kill;
    }

    /**
     * Sets the value of the kill property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setKill(NoParamType value) {
        this.kill = value;
    }

    /**
     * Gets the value of the getReadCyclesPerTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetReadCyclesPerTrigger() {
        return getReadCyclesPerTrigger;
    }

    /**
     * Sets the value of the getReadCyclesPerTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetReadCyclesPerTrigger(IntReturnType value) {
        this.getReadCyclesPerTrigger = value;
    }

    /**
     * Gets the value of the setReadCyclesPerTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetReadCyclesPerTrigger() {
        return setReadCyclesPerTrigger;
    }

    /**
     * Sets the value of the setReadCyclesPerTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetReadCyclesPerTrigger(NoParamType value) {
        this.setReadCyclesPerTrigger = value;
    }

    /**
     * Gets the value of the getMaxReadDutyCycle property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetMaxReadDutyCycle() {
        return getMaxReadDutyCycle;
    }

    /**
     * Sets the value of the getMaxReadDutyCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetMaxReadDutyCycle(IntReturnType value) {
        this.getMaxReadDutyCycle = value;
    }

    /**
     * Gets the value of the setMaxReadDutyCycle property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetMaxReadDutyCycle() {
        return setMaxReadDutyCycle;
    }

    /**
     * Sets the value of the setMaxReadDutyCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetMaxReadDutyCycle(NoParamType value) {
        this.setMaxReadDutyCycle = value;
    }

    /**
     * Gets the value of the getReadTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetReadTimeout() {
        return getReadTimeout;
    }

    /**
     * Sets the value of the getReadTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetReadTimeout(IntReturnType value) {
        this.getReadTimeout = value;
    }

    /**
     * Gets the value of the setReadTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetReadTimeout() {
        return setReadTimeout;
    }

    /**
     * Sets the value of the setReadTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetReadTimeout(NoParamType value) {
        this.setReadTimeout = value;
    }

    /**
     * Gets the value of the getSession property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetSession() {
        return getSession;
    }

    /**
     * Sets the value of the getSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetSession(IntReturnType value) {
        this.getSession = value;
    }

    /**
     * Gets the value of the setSession property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetSession() {
        return setSession;
    }

    /**
     * Sets the value of the setSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetSession(NoParamType value) {
        this.setSession = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returnValue" type="{urn:epcglobal:rp:xsd:1}ReadReportType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "returnValue"
    })
    public static class RawReadIDs {

        protected ReadReportType returnValue;

        /**
         * Gets the value of the returnValue property.
         * 
         * @return
         *     possible object is
         *     {@link ReadReportType }
         *     
         */
        public ReadReportType getReturnValue() {
            return returnValue;
        }

        /**
         * Sets the value of the returnValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReadReportType }
         *     
         */
        public void setReturnValue(ReadReportType value) {
            this.returnValue = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returnValue" type="{urn:epcglobal:rp:xsd:1}ReadReportType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "returnValue"
    })
    public static class Read {

        protected ReadReportType returnValue;

        /**
         * Gets the value of the returnValue property.
         * 
         * @return
         *     possible object is
         *     {@link ReadReportType }
         *     
         */
        public ReadReportType getReturnValue() {
            return returnValue;
        }

        /**
         * Sets the value of the returnValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReadReportType }
         *     
         */
        public void setReturnValue(ReadReportType value) {
            this.returnValue = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="returnValue" type="{urn:epcglobal:rp:xsd:1}ReadReportType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(AccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "returnValue"
    })
    public static class ReadIDs {

        protected ReadReportType returnValue;

        /**
         * Gets the value of the returnValue property.
         * 
         * @return
         *     possible object is
         *     {@link ReadReportType }
         *     
         */
        public ReadReportType getReturnValue() {
            return returnValue;
        }

        /**
         * Sets the value of the returnValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReadReportType }
         *     
         */
        public void setReturnValue(ReadReportType value) {
            this.returnValue = value;
        }

    }

}
