/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Accada (www.accada.org).
 *
 * Accada is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Accada is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Accada; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.05 at 05:26:35 PM CEST 
//


package org.accada.reader.rprm.core.msg.reply;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import org.accada.reader.rprm.core.msg.reply.IntReturnType;
import org.accada.reader.rprm.core.msg.reply.NoParamType;
import org.accada.reader.rprm.core.msg.reply.StringReturnType;
import org.accada.reader.rprm.core.msg.reply.TagFieldReply;
import org.accada.reader.rprm.core.msg.reply.TagFieldReturnType;


/**
 * <p>Java class for TagFieldReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TagFieldReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="create" type="{urn:epcglobal:rp:xsd:1}TagFieldReturnType"/>
 *         &lt;element name="getName" type="{urn:epcglobal:rp:xsd:1}stringReturnType"/>
 *         &lt;element name="getTagFieldName" type="{urn:epcglobal:rp:xsd:1}stringReturnType"/>
 *         &lt;element name="setTagFieldName" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getMemoryBank" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setMemoryBank" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getOffset" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setOffset" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *         &lt;element name="getLength" type="{urn:epcglobal:rp:xsd:1}intReturnType"/>
 *         &lt;element name="setLength" type="{urn:epcglobal:rp:xsd:1}noParamType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "TagFieldReply", propOrder = {
    "create",
    "getName",
    "getTagFieldName",
    "setTagFieldName",
    "getMemoryBank",
    "setMemoryBank",
    "getOffset",
    "setOffset",
    "getLength",
    "setLength"
})
public class TagFieldReply {

    protected TagFieldReturnType create;
    protected StringReturnType getName;
    protected StringReturnType getTagFieldName;
    protected NoParamType setTagFieldName;
    protected IntReturnType getMemoryBank;
    protected NoParamType setMemoryBank;
    protected IntReturnType getOffset;
    protected NoParamType setOffset;
    protected IntReturnType getLength;
    protected NoParamType setLength;

    /**
     * Gets the value of the create property.
     * 
     * @return
     *     possible object is
     *     {@link TagFieldReturnType }
     *     
     */
    public TagFieldReturnType getCreate() {
        return create;
    }

    /**
     * Sets the value of the create property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagFieldReturnType }
     *     
     */
    public void setCreate(TagFieldReturnType value) {
        this.create = value;
    }

    /**
     * Gets the value of the getName property.
     * 
     * @return
     *     possible object is
     *     {@link StringReturnType }
     *     
     */
    public StringReturnType getGetName() {
        return getName;
    }

    /**
     * Sets the value of the getName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringReturnType }
     *     
     */
    public void setGetName(StringReturnType value) {
        this.getName = value;
    }

    /**
     * Gets the value of the getTagFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link StringReturnType }
     *     
     */
    public StringReturnType getGetTagFieldName() {
        return getTagFieldName;
    }

    /**
     * Sets the value of the getTagFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringReturnType }
     *     
     */
    public void setGetTagFieldName(StringReturnType value) {
        this.getTagFieldName = value;
    }

    /**
     * Gets the value of the setTagFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetTagFieldName() {
        return setTagFieldName;
    }

    /**
     * Sets the value of the setTagFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetTagFieldName(NoParamType value) {
        this.setTagFieldName = value;
    }

    /**
     * Gets the value of the getMemoryBank property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetMemoryBank() {
        return getMemoryBank;
    }

    /**
     * Sets the value of the getMemoryBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetMemoryBank(IntReturnType value) {
        this.getMemoryBank = value;
    }

    /**
     * Gets the value of the setMemoryBank property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetMemoryBank() {
        return setMemoryBank;
    }

    /**
     * Sets the value of the setMemoryBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetMemoryBank(NoParamType value) {
        this.setMemoryBank = value;
    }

    /**
     * Gets the value of the getOffset property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetOffset() {
        return getOffset;
    }

    /**
     * Sets the value of the getOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetOffset(IntReturnType value) {
        this.getOffset = value;
    }

    /**
     * Gets the value of the setOffset property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetOffset() {
        return setOffset;
    }

    /**
     * Sets the value of the setOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetOffset(NoParamType value) {
        this.setOffset = value;
    }

    /**
     * Gets the value of the getLength property.
     * 
     * @return
     *     possible object is
     *     {@link IntReturnType }
     *     
     */
    public IntReturnType getGetLength() {
        return getLength;
    }

    /**
     * Sets the value of the getLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntReturnType }
     *     
     */
    public void setGetLength(IntReturnType value) {
        this.getLength = value;
    }

    /**
     * Gets the value of the setLength property.
     * 
     * @return
     *     possible object is
     *     {@link NoParamType }
     *     
     */
    public NoParamType getSetLength() {
        return setLength;
    }

    /**
     * Sets the value of the setLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoParamType }
     *     
     */
    public void setSetLength(NoParamType value) {
        this.setLength = value;
    }

}
