/*
 * Copyright (C) 2007 ETH Zurich
 *
 * This file is part of Fosstrak (www.fosstrak.org).
 *
 * Fosstrak is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1, as published by the Free Software Foundation.
 *
 * Fosstrak is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Fosstrak; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.21 at 05:25:46 PM CEST 
//


package org.fosstrak.reader.rp.proxy.configurator;

import javax.xml.bind.annotation.XmlRegistry;

import org.fosstrak.reader.rp.proxy.configurator.DataSelectorConfiguration.EventFilters;
import org.fosstrak.reader.rp.proxy.configurator.DataSelectorConfiguration.FieldNames;
import org.fosstrak.reader.rp.proxy.configurator.DataSelectorConfiguration.TagFields;
import org.fosstrak.reader.rp.proxy.configurator.NotificationChannelConfiguration.NotificationTriggers;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.fosstrak.reader.proxy.configurator package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.fosstrak.reader.proxy.configurator
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotificationChannels }
     * 
     */
    public NotificationChannels createNotificationChannels() {
        return new NotificationChannels();
    }

    /**
     * Create an instance of {@link IOEdgeTriggerConfiguration }
     * 
     */
    public IOEdgeTriggerConfiguration createIOEdgeTriggerConfiguration() {
        return new IOEdgeTriggerConfiguration();
    }

    /**
     * Create an instance of {@link org.fosstrak.reader.rp.proxy.configurator.NotificationChannelConfiguration.Sources }
     * 
     */
    public org.fosstrak.reader.rp.proxy.configurator.NotificationChannelConfiguration.Sources createNotificationChannelConfigurationSources() {
        return new org.fosstrak.reader.rp.proxy.configurator.NotificationChannelConfiguration.Sources();
    }

    /**
     * Create an instance of {@link NotificationChannelConfiguration }
     * 
     */
    public NotificationChannelConfiguration createNotificationChannelConfiguration() {
        return new NotificationChannelConfiguration();
    }

    /**
     * Create an instance of {@link DataSelectorConfiguration }
     * 
     */
    public DataSelectorConfiguration createDataSelectorConfiguration() {
        return new DataSelectorConfiguration();
    }

    /**
     * Create an instance of {@link FieldNames }
     * 
     */
    public FieldNames createDataSelectorConfigurationFieldNames() {
        return new FieldNames();
    }

    /**
     * Create an instance of {@link TagFields }
     * 
     */
    public TagFields createDataSelectorConfigurationTagFields() {
        return new TagFields();
    }

    /**
     * Create an instance of {@link ContinuousTriggerConfiguration }
     * 
     */
    public ContinuousTriggerConfiguration createContinuousTriggerConfiguration() {
        return new ContinuousTriggerConfiguration();
    }

    /**
     * Create an instance of {@link TimerTriggerConfiguration }
     * 
     */
    public TimerTriggerConfiguration createTimerTriggerConfiguration() {
        return new TimerTriggerConfiguration();
    }

    /**
     * Create an instance of {@link ReaderDeviceConfiguration }
     * 
     */
    public ReaderDeviceConfiguration createReaderDeviceConfiguration() {
        return new ReaderDeviceConfiguration();
    }

    /**
     * Create an instance of {@link NotificationTriggers }
     * 
     */
    public NotificationTriggers createNotificationChannelConfigurationNotificationTriggers() {
        return new NotificationTriggers();
    }

    /**
     * Create an instance of {@link org.fosstrak.reader.rp.proxy.configurator.Sources }
     * 
     */
    public org.fosstrak.reader.rp.proxy.configurator.Sources createSources() {
        return new org.fosstrak.reader.rp.proxy.configurator.Sources();
    }

    /**
     * Create an instance of {@link SourceConfiguration }
     * 
     */
    public SourceConfiguration createSourceConfiguration() {
        return new SourceConfiguration();
    }

    /**
     * Create an instance of {@link DataSelectors }
     * 
     */
    public DataSelectors createDataSelectors() {
        return new DataSelectors();
    }

    /**
     * Create an instance of {@link ConfigurationDocument }
     * 
     */
    public ConfigurationDocument createConfigurationDocument() {
        return new ConfigurationDocument();
    }

    /**
     * Create an instance of {@link IOValueTriggerConfiguration }
     * 
     */
    public IOValueTriggerConfiguration createIOValueTriggerConfiguration() {
        return new IOValueTriggerConfiguration();
    }

    /**
     * Create an instance of {@link EventFilters }
     * 
     */
    public EventFilters createDataSelectorConfigurationEventFilters() {
        return new EventFilters();
    }

    /**
     * Create an instance of {@link ReaderConfiguration }
     * 
     */
    public ReaderConfiguration createReaderConfiguration() {
        return new ReaderConfiguration();
    }

    /**
     * Create an instance of {@link Triggers }
     * 
     */
    public Triggers createTriggers() {
        return new Triggers();
    }

}
